/*
    Starship Raycaster - A GPU-accelerated raycasting demo built with SDL3 and Vulkan.
    Copyright (C) 2026 Walter W. Whitman aka The Joyful Programmer (tm)
    Copyright (C) 2026 AstroCosmic Systems (tm)
    Copyright (C) 2026 Mini Yorkies Software (tm)

    This software is provided 'as-is', without any express or implied
    warranty.  In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.

    2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.

    3. This notice may not be removed or altered from any source distribution.

    This project is my attempt to build a modern GPU-accelerated raycasting demo
    in the spirit of classic 90s "2.5D" shooters, with a single-deck ship map as
    the main game overlay. It's also a personal sandbox for learning Vulkan and
    SDL3, and a testbed for various palette-building and quantization techniques.

    The code is organized into a few main components:
    - main.cpp: SDL3 app entrypoint and event loop, forwarding to App.
    - starship_raycaster.hpp/cpp: The main application class, Vulkan setup,
        rendering loop, and game overlay logic.
    - star_shipgen.hpp/cpp: A BSP-based procedural ship map generator, producing
        a grid of "tiles" that the raycaster renders.
    - star_palette.hpp/cpp: CPU palette-building utilities, including a perceptual
        palette builder based on a GPU-accelerated histogram.

    The project is built with C++26, and uses the Vulkan graphics API for rendering
    and SDL3 for windowing and input. It should compile and run on Windows, Linux,
    and macOS (with Vulkan support).

    The code is licensed under the zlib License (see above), which allows for free
    use and modification with minimal restrictions. Attribution is appreciated but
    not required.

    The testbed of palette-building techniques is a key part of the project, and includes:
    - A GPU-accelerated histogram builder that computes a 33^3 color histogram of
      the rendered image.
    - A CPU palette builder that takes the histogram and produces a 256-color palette
      using a weighted median-cut algorithm.
    - Support for preset palettes (e.g. EGA/VGA) and various dithering algorithms
      (Floyd-Steinberg, Bayer matrix, etc.).
    - A final display pass that looks up palette indices to show the quantized image.
    
    The game overlay is a simple GPU raycaster that renders a 2D grid-based map of "tiles"
    into a 3D view. The map is generated by a BSP-based algorithm that creates rooms,
    corridors, and zones with different themes. The raycaster supports walls, doors,
    stairs, and sprites (for NPCs or decorations). The player can move around the map and
    interact with doors.
    
    The project is a work in progress and may contain rough edges or incomplete features.
    
    Enjoy exploring the code and the demo!
*/
#version 450
layout(location = 0) out vec4 outColor;

// --- Bindings (match the existing gui overlay pipeline) ---
// 0: Map SSBO (uint per cell)
layout(set = 0, binding = 0, std430) readonly buffer GameMap
{
    uint cell[];
} gMap;

// 1: HUD atlas
layout(set = 0, binding = 1) uniform sampler2D uHudAtlas;

// 2: Legend atlas
layout(set = 0, binding = 2) uniform sampler2D uLegendAtlas;

// --- Push constants ---
// NOTE: This is 80 bytes (vec4*3 + uvec4 + vec4).
layout(push_constant) uniform Push
{
    vec4  a; // (renderW, renderH, timeSeconds, guiEnabled)
    vec4  b; // (playerX, playerY, playerAngleRadians, minimapCorner)
    vec4  c; // (health0to100, ammo, minimapSizePx, fullMapFade 0..1)
    uvec4 d; // (mapW, mapH, crtMode, flags)
    vec4  e; // (fullMapPanX_cells, fullMapPanY_cells, fullMapZoom, reserved)
} pc;

float sat(float x) { return clamp(x, 0.0, 1.0); }

// Straight-alpha over
vec4 overStraight(vec4 under, vec4 over)
{
    vec3 u = under.rgb * under.a;
    vec3 o = over.rgb  * over.a;
    float outA = over.a + under.a * (1.0 - over.a);
    vec3 outP = o + u * (1.0 - over.a);
    vec3 outRGB = (outA > 1e-6) ? (outP / outA) : vec3(0.0);
    return vec4(outRGB, outA);
}

uint  crtMode()       { return pc.d.z; }
uint  guiFlags()      { return pc.d.w; }
bool  crtLegendOn()   { return (guiFlags() & 1u) != 0u; }
float hintAlpha()     { return float((guiFlags() >> 8) & 255u) / 255.0; }

float hash21(vec2 p)
{
    p = fract(p * vec2(123.34, 456.21));
    p += dot(p, p + 34.345);
    return fract(p.x * p.y);
}

vec2 barrelWarp(vec2 uv, float k)
{
    vec2 q = uv * 2.0 - 1.0;
    float r2 = dot(q, q);
    q *= 1.0 + k * r2;
    return q * 0.5 + 0.5;
}

float boxMask(vec2 p, vec2 center, vec2 halfSize)
{
    vec2 q = abs(p - center) - halfSize;
    return 1.0 - step(0.0, max(q.x, q.y));
}

float borderMask(vec2 p, vec2 center, vec2 halfSize, float thickness)
{
    vec2 q = abs(p - center) - halfSize;
    float inside = 1.0 - step(0.0, max(q.x, q.y));
    float d = min(abs(q.x), abs(q.y));
    float b = 1.0 - step(thickness, d);
    return inside * b;
}

vec4 sampleHudTile(int tileIndex, vec2 uv01)
{
    const float GRID = 16.0;
    float tx = float(tileIndex % 16);
    float ty = float(tileIndex / 16);

    vec2 uv = (vec2(tx, ty) + clamp(uv01, 0.0, 1.0)) / GRID;
    return texture(uHudAtlas, uv);
}

vec4 drawTile(int tileIndex, vec2 fragPx, vec2 posPx, float sizePx)
{
    vec2 p = fragPx - posPx;
    if (p.x < 0.0 || p.y < 0.0 || p.x >= sizePx || p.y >= sizePx) return vec4(0.0);
    vec2 uv = p / sizePx;
    return sampleHudTile(tileIndex, uv);
}

vec4 drawNumber(vec2 fragPx, vec2 posPx, float sizePx, int value, int digitsMax)
{
    int v = max(value, 0);

    int digs = 1;
    int t = v;
    while (t >= 10 && digs < digitsMax) { t /= 10; digs++; }

    vec4 accum = vec4(0.0);
    float x = posPx.x;
    for (int i = digs - 1; i >= 0; --i)
    {
        int pow10 = 1;
        for (int k = 0; k < i; ++k) pow10 *= 10;
        int digit = (v / pow10) % 10;

        vec4 s = drawTile(digit, fragPx, vec2(x, posPx.y), sizePx);
        accum = overStraight(accum, s);
        x += sizePx;
    }
    return accum;
}

uint mapCell(uint x, uint y)
{
    uint W = pc.d.x;
    uint idx = y * W + x;
    return gMap.cell[idx];
}

uint cellType(uint c)   { return (c & 0xFFu); }
uint doorOpen8(uint c)  { return (c >> 8) & 0xFFu; }
bool cellLocked(uint c) { return ((c >> 16) & 1u) != 0u; }
uint cellZone(uint c)   { return (c >> 17) & 0xFFu; }

bool isWalkable(uint t)
{
    return (t == 0u || t == 5u || t == 6u); // empty / stairs etc.
}

vec3 zoneColor(uint z)
{
    if (z == 1u)   return vec3(0.22, 0.60, 0.30);
    if (z == 2u)   return vec3(0.25, 0.42, 0.78);
    if (z == 3u)   return vec3(0.78, 0.26, 0.22);
    if (z == 4u)   return vec3(0.70, 0.55, 0.25);
    if (z == 5u)   return vec3(0.22, 0.72, 0.60);
    if (z == 6u)   return vec3(0.80, 0.70, 0.28);
    if (z == 7u)   return vec3(0.62, 0.30, 0.80);
    if (z == 8u)   return vec3(0.32, 0.62, 0.78);
    if (z == 200u) return vec3(0.26, 0.44, 0.42);
    return vec3(0.16, 0.16, 0.18);
}

// Health gradient: 100% green, 50% yellow, 0% red, dead = dark red.
vec3 healthToColor(float health01)
{
    health01 = sat(health01);
    vec3 green  = vec3(0.10, 0.95, 0.18);
    vec3 yellow = vec3(1.00, 0.95, 0.10);
    vec3 red    = vec3(1.00, 0.12, 0.10);

    vec3 c;
    if (health01 >= 0.5)
    {
        float u = (health01 - 0.5) / 0.5;
        c = mix(yellow, green, u);
    }
    else
    {
        float u = health01 / 0.5;
        c = mix(red, yellow, u);
    }

    if (health01 <= 0.001)
        c = vec3(0.28, 0.02, 0.02);

    return c;
}

// Distance point->segment
float sdSegment(vec2 p, vec2 a, vec2 b)
{
    vec2 pa = p - a;
    vec2 ba = b - a;
    float h = sat(dot(pa, ba) / max(1e-6, dot(ba, ba)));
    return length(pa - ba * h);
}

// Filled triangle mask, anti-aliased.
// p is in triangle-local space (pixels), triangle points +X.
float triFilledMask(vec2 p, float sizePx)
{
    vec2 v0 = vec2( sizePx * 1.00, 0.0);
    vec2 v1 = vec2(-sizePx * 0.70,  sizePx * 0.78);
    vec2 v2 = vec2(-sizePx * 0.70, -sizePx * 0.78);

    vec2 e0 = v1 - v0;
    vec2 e1 = v2 - v1;
    vec2 e2 = v0 - v2;

    float s0 = e0.x * (p.y - v0.y) - e0.y * (p.x - v0.x);
    float s1 = e1.x * (p.y - v1.y) - e1.y * (p.x - v1.x);
    float s2 = e2.x * (p.y - v2.y) - e2.y * (p.x - v2.x);

    float inA = step(0.0, s0) * step(0.0, s1) * step(0.0, s2);
    float inB = step(s0, 0.0) * step(s1, 0.0) * step(s2, 0.0);
    float inside = max(inA, inB);

    float d0 = sdSegment(p, v0, v1);
    float d1 = sdSegment(p, v1, v2);
    float d2 = sdSegment(p, v2, v0);
    float dEdge = min(d0, min(d1, d2));

    // 1px AA band
    float aa = 1.0;
    float edgeFill = smoothstep(0.0, aa, dEdge); // 0 at edge, 1 inside by aa pixels

    return inside * edgeFill;
}

vec4 sampleMapAbs(ivec2 mapCellI, ivec2 mapDim, vec3 bg)
{
    vec3 col = bg;
    float a = 0.82;

    if (mapCellI.x >= 0 && mapCellI.y >= 0 && mapCellI.x < mapDim.x && mapCellI.y < mapDim.y)
    {
        uint c = mapCell(uint(mapCellI.x), uint(mapCellI.y));
        uint t = cellType(c);
        uint z = cellZone(c);
        vec3 zc = zoneColor(z);

        if (t == 4u) // door
        {
            bool locked = cellLocked(c);
            float open01 = float(doorOpen8(c)) / 255.0;
            vec3 doorCol = vec3(0.70, 0.55, 0.20) + vec3(0.10) * (1.0 - open01);
            doorCol = mix(doorCol, zc, 0.45);
            if (locked)
                doorCol = mix(doorCol, vec3(0.95, 0.20, 0.20), 0.80);
            col = mix(bg, doorCol, 0.95);
        }
        else if (isWalkable(t))
        {
            col = mix(bg, zc, 0.90);
        }
        else
        {
            // Medium gray walls everywhere
            vec3 wall = vec3(0.55, 0.56, 0.58);
            col = mix(bg, wall, 0.93);
        }
    }

    return vec4(col, a);
}

// --- Minimap ---
vec4 drawMinimap(vec2 fragPx)
{
    float sizePx = max(64.0, pc.c.z);
    float pad = 14.0;

    float w = pc.a.x;
    float h = pc.a.y;

    int pos = int(pc.b.w + 0.5);

    vec2 origin;
    if (pos == 0) origin = vec2(pad, pad);
    else if (pos == 1) origin = vec2(w - pad - sizePx, pad);
    else if (pos == 2) origin = vec2(pad, h - pad - sizePx);
    else origin = vec2(w - pad - sizePx, h - pad - sizePx);

    vec2 center = origin + vec2(sizePx * 0.5);
    float inside = boxMask(fragPx, center, vec2(sizePx * 0.5));
    if (inside < 0.5) return vec4(0.0);

    vec3 bg = vec3(0.03, 0.035, 0.04);

    float cellPx = 2.0;
    int VIEW = int(floor(sizePx / cellPx));
    VIEW = max(VIEW, 21);
    if ((VIEW & 1) == 0) VIEW -= 1;
    int HALF = VIEW / 2;

    float mapPx = float(VIEW) * cellPx;
    vec2 originGrid = origin + vec2(floor((sizePx - mapPx) * 0.5));

    vec2 local = fragPx - originGrid;
    ivec2 miniCell = ivec2(floor(local / cellPx));

    if (miniCell.x < 0 || miniCell.y < 0 || miniCell.x >= VIEW || miniCell.y >= VIEW)
    {
        float b = borderMask(fragPx, center, vec2(sizePx * 0.5), 1.5);
        return vec4(bg, 0.65) + vec4(vec3(0.9) * b, b);
    }

    ivec2 mapDim = ivec2(int(pc.d.x), int(pc.d.y));
    ivec2 playerCell = ivec2(floor(pc.b.xy));
    ivec2 mapCellI = playerCell + miniCell - ivec2(HALF);

    vec4 s = sampleMapAbs(mapCellI, mapDim, bg);
    vec3 col = s.rgb;
    float a = 0.70;

    // Player triangle at minimap center
    vec2 playerCenterPx = originGrid + (vec2(HALF) + vec2(0.5)) * cellPx;

    float hp01 = sat(pc.c.x / 100.0);
    vec3 pCol = healthToColor(hp01);

    float t = pc.a.z;
    float lumPulse = 0.78 + 0.22 * sin(t * 5.6);
    float sizePulse = 1.0 + 0.06 * sin(t * 4.2);

    // rotate p into triangle-local space
    vec2 dp = fragPx - playerCenterPx;
    float ca = cos(pc.b.z), sa = sin(pc.b.z);
    vec2 pl = vec2( ca*dp.x + sa*dp.y, -sa*dp.x + ca*dp.y );

    float triSize = 7.5 * sizePulse;
    float mTri = triFilledMask(pl, triSize);

    col = mix(col, pCol * lumPulse, mTri);

    float b = borderMask(fragPx, center, vec2(sizePx * 0.5), 1.5);
    vec3 outRgb = mix(col, vec3(0.95), b);
    return vec4(outRgb, a);
}

// --- Full TACTICAL map ---
// Fit-to-screen at zoom=1, zoom/pan in CELL UNITS.
// pc.e.xy = panCells, pc.e.z = zoom
vec4 drawFullMap(vec2 fragPx)
{
    float fade = sat(pc.c.w);
    if (fade <= 0.001) return vec4(0.0);

    float w = pc.a.x;
    float h = pc.a.y;

    vec3 bg = vec3(0.015, 0.017, 0.020);
    vec4 base = vec4(bg, 0.62 * fade);

    ivec2 mapDim = ivec2(int(pc.d.x), int(pc.d.y));
    vec2 mapDimF = vec2(mapDim);

    float zoom = max(0.01, pc.e.z);

    // Fit-to-screen baseline at zoom=1
    float fit = 0.92 * min(w / max(1.0, mapDimF.x), h / max(1.0, mapDimF.y));
    fit = max(fit, 0.05);

    float cellPx = fit * zoom;

    vec2 center = vec2(w, h) * 0.5;
    vec2 mapCenterCell = mapDimF * 0.5;

    // Pan is in CELLS.
    vec2 panCells = pc.e.xy;

    // Map origin of cell (0,0) in screen pixels:
    vec2 origin = center - mapCenterCell * cellPx + panCells * cellPx;

    vec2 local = fragPx - origin;

    // Convert to map UV in rect
    vec2 mapF = local / max(1e-6, cellPx);

    // Darken outside map
    if (mapF.x < 0.0 || mapF.y < 0.0 || mapF.x >= mapDimF.x || mapF.y >= mapDimF.y)
        return base;

    // CRT seasoning on map (optional)
    uint m = crtMode();
    vec2 uv = mapF / mapDimF;
    vec2 uvW = uv;

    float t = pc.a.z;

    if (m > 0u)
    {
        float k = (m == 1u) ? 0.07 : (m == 2u) ? 0.12 : 0.17;
        uvW = barrelWarp(uvW, k);

        float wob = sin((uvW.y * 860.0) + t * 24.0) * 0.00055;
        wob += sin((uvW.y * 120.0) + t * 7.0) * 0.00035;
        uvW.x += wob * (m == 1u ? 0.6 : m == 2u ? 1.0 : 1.3);
    }

    vec2 mapFW = uvW * mapDimF;
    ivec2 mapCellI = ivec2(floor(mapFW));

    vec3 col;
    float a;

    if (m == 0u)
    {
        vec4 s = sampleMapAbs(mapCellI, mapDim, bg);
        col = s.rgb; a = s.a;
    }
    else
    {
        float chroma = (m == 1u) ? 0.0016 : (m == 2u) ? 0.0036 : 0.0065;
        vec2 cOff = vec2(chroma, chroma * 0.55);
        cOff *= (0.65 + 0.35 * sin(t * 1.7));

        ivec2 mR = ivec2(floor(((uvW + cOff) * mapDimF)));
        ivec2 mG = ivec2(floor(((uvW)        * mapDimF)));
        ivec2 mB = ivec2(floor(((uvW - cOff) * mapDimF)));

        vec4 sR = sampleMapAbs(mR, mapDim, bg);
        vec4 sG = sampleMapAbs(mG, mapDim, bg);
        vec4 sB = sampleMapAbs(mB, mapDim, bg);

        col = vec3(sR.r, sG.g, sB.b);
        a = max(sG.a, max(sR.a, sB.a));
    }

    // Player marker at true map position
    vec2 playerCell = floor(pc.b.xy) + vec2(0.5);
    vec2 playerPx = origin + playerCell * cellPx;

    float hp01 = sat(pc.c.x / 100.0);
    vec3 pCol = healthToColor(hp01);

    float lumPulse = 0.78 + 0.22 * sin(t * 5.6);
    float sizePulse = 1.0 + 0.08 * sin(t * 4.2);

    float triSize = max(8.0, cellPx * 2.1) * sizePulse;

    vec2 dp = fragPx - playerPx;
    float ca = cos(pc.b.z), sa = sin(pc.b.z);
    vec2 pl = vec2( ca*dp.x + sa*dp.y, -sa*dp.x + ca*dp.y );

    float mTri = triFilledMask(pl, triSize);
    col = mix(col, pCol * lumPulse, mTri);

    // Scanlines + noise
    if (m > 0u)
    {
        float scanStr = (m == 1u) ? 0.08 : (m == 2u) ? 0.14 : 0.22;
        float scan = 1.0 - scanStr * (0.5 + 0.5 * sin(fragPx.y * 1.8 + t * 22.0));

        float nStr = (m == 1u) ? 0.018 : (m == 2u) ? 0.040 : 0.075;
        float n = hash21(fragPx * vec2(0.07, 0.11) + vec2(t * 12.7, t * 3.1));
        vec3 noiseRGB = (n - 0.5) * nStr + vec3(n * nStr * 0.55);

        col *= scan;
        col += noiseRGB;
    }

    return overStraight(base, vec4(clamp(col, 0.0, 1.0), a * fade));
}

vec4 drawLegend(vec2 fragPx)
{
    float fade = sat(pc.c.w);
    if (fade <= 0.001) return vec4(0.0);

    const vec2 panelSz = vec2(420.0, 380.0);
    const vec2 panelPos = vec2(14.0, 14.0);

    vec2 local = fragPx - panelPos;
    if (local.x < 0.0 || local.y < 0.0 || local.x >= panelSz.x || local.y >= panelSz.y)
        return vec4(0.0);

    vec2 uv = local / panelSz;
    vec2 atlasUV = uv * (panelSz / vec2(512.0, 512.0));

    vec4 c0 = texture(uLegendAtlas, atlasUV);

    if (crtLegendOn() && crtMode() > 0u)
    {
        uint m = crtMode();
        float t = pc.a.z;
        float k = (m == 1u) ? 0.03 : (m == 2u) ? 0.05 : 0.07;
        vec2 u2 = barrelWarp(uv, k);
        float wob = sin((u2.y * 520.0) + t * 19.0) * 0.00045;
        u2.x += wob;
        vec2 a2 = u2 * (panelSz / vec2(512.0, 512.0));

        float chroma = (m == 1u) ? 0.0010 : (m == 2u) ? 0.0018 : 0.0028;
        vec2 off = vec2(chroma, 0.0);
        vec4 r = texture(uLegendAtlas, a2 + off);
        vec4 g = texture(uLegendAtlas, a2);
        vec4 b = texture(uLegendAtlas, a2 - off);
        c0 = vec4(r.r, g.g, b.b, max(g.a, max(r.a, b.a)));

        float scanStr = (m == 1u) ? 0.06 : (m == 2u) ? 0.10 : 0.15;
        float scan = 1.0 - scanStr * (0.5 + 0.5 * sin((fragPx.y * 1.8) + t * 22.0));
        c0.rgb *= scan;
    }

    c0.a *= fade;
    return c0;
}

// Hint strip in legend atlas
vec4 drawMouseHint(vec2 fragPx)
{
    float ha = hintAlpha();
    if (ha <= 0.001) return vec4(0.0);

    float w = pc.a.x;
    float h = pc.a.y;

    const vec2 hintSz = vec2(512.0, 84.0);
    vec2 hintPos = vec2(floor((w - hintSz.x) * 0.5), h - 18.0 - hintSz.y);
    vec2 local = fragPx - hintPos;
    if (local.x < 0.0 || local.y < 0.0 || local.x >= hintSz.x || local.y >= hintSz.y)
        return vec4(0.0);

    vec2 uv = local / hintSz;

    // If you moved the hint strip down, change this Y.
    // Suggested: y = 392/512. Original was 352/512.
    float hintY = 392.0 / 512.0;
    vec2 atlasUV = vec2(uv.x, hintY + uv.y * (84.0 / 512.0));

    vec4 c0 = texture(uLegendAtlas, atlasUV);

    float t = pc.a.z;
    float scan = 0.92 + 0.08 * sin((fragPx.y * 1.7) + t * 18.0);
    c0.rgb *= scan;
    c0.a *= ha;
    return c0;
}

vec4 drawHudPanel(vec2 fragPx)
{
    float w = pc.a.x;
    float h = pc.a.y;

    vec2 panelTL = vec2(14.0, h - 14.0 - 88.0);
    vec2 panelSize = vec2(290.0, 88.0);
    vec2 center = panelTL + panelSize * 0.5;

    float inside = boxMask(fragPx, center, panelSize * 0.5);
    if (inside < 0.5) return vec4(0.0);

    float pulse = 0.90 + 0.10 * (0.5 + 0.5 * sin(pc.a.z * 3.2));

    vec3 bg = vec3(0.03, 0.03, 0.035) * pulse;
    float b = borderMask(fragPx, center, panelSize * 0.5, 1.5);

    vec3 rgb = mix(bg, vec3(0.95), b);
    float a = 0.72;

    float tile = 28.0;
    vec2 iconPos = panelTL + vec2(14.0, 14.0);
    vec4 heart = drawTile(14, fragPx, iconPos, tile);

    vec2 numPos = iconPos + vec2(tile + 10.0, 0.0);
    int hp = int(pc.c.x + 0.5);
    vec4 hpNum = drawNumber(fragPx, numPos, tile, hp, 3);

    vec2 iconPos2 = panelTL + vec2(14.0, 14.0 + tile + 10.0);
    vec4 bullet = drawTile(15, fragPx, iconPos2, tile);

    vec2 numPos2 = iconPos2 + vec2(tile + 10.0, 0.0);
    int am = int(pc.c.y + 0.5);
    vec4 amNum = drawNumber(fragPx, numPos2, tile, am, 3);

    vec4 accum = vec4(rgb, a);
    accum = overStraight(accum, heart);
    accum = overStraight(accum, hpNum);
    accum = overStraight(accum, bullet);
    accum = overStraight(accum, amNum);

    return accum;
}

vec4 drawCrosshair(vec2 fragPx)
{
    float w = pc.a.x;
    float h = pc.a.y;

    vec2 c = vec2(w, h) * 0.5;

    float crossLen = max(7.0, min(w, h) * 0.02);
    float thick = 1.2;

    float dx = abs(fragPx.x - c.x);
    float dy = abs(fragPx.y - c.y);

    float vLine = (1.0 - step(thick, dx)) * (1.0 - step(crossLen, dy));
    float hLine = (1.0 - step(thick, dy)) * (1.0 - step(crossLen, dx));

    float mask = max(vLine, hLine);
    float pulse = 0.75 + 0.25 * (0.5 + 0.5 * sin(pc.a.z * 5.5));

    vec3 col = vec3(1.0) * pulse;
    return vec4(col, mask * 0.65);
}

float segMask(vec2 p, vec2 a, vec2 b, float thick)
{
    float d = sdSegment(p, a, b);
    return sat(1.0 - smoothstep(thick, thick + 1.0, d));
}

vec2 rot(vec2 v, float a)
{
    float c = cos(a), s = sin(a);
    return vec2(c*v.x - s*v.y, s*v.x + c*v.y);
}

// Compass rose rotates, letters ORBIT WITH IT but stay upright (screen-up).
vec4 drawCompassRose(vec2 fragPx)
{
    float w = pc.a.x;
    float t = pc.a.z;

    float R = 56.0;
    vec2 center = vec2(w * 0.5, 28.0 + R);

    vec2 p = fragPx - center;

    float ang = pc.b.z;

    // Rose geometry uses rotated space
    vec2 pr = rot(p, -ang);
    float r = length(pr);

    float ring = sat(1.0 - smoothstep(R, R + 1.5, r)) * sat(smoothstep(R - 2.5, R - 1.0, r));
    float r2 = R * 0.72;
    float ring2 = sat(1.0 - smoothstep(r2, r2 + 1.2, r)) * sat(smoothstep(r2 - 2.0, r2 - 0.8, r));

    float spike = 0.0;
    for (int i = 0; i < 16; ++i)
    {
        float a = 6.2831853 * (float(i) / 16.0);
        vec2 d = vec2(cos(a), sin(a));
        float len = (i % 2 == 0) ? (R * 0.98) : (R * 0.72);
        float baseW = (i % 2 == 0) ? 12.0 : 7.0;

        float along = dot(pr, d);
        float perp = abs(pr.x * d.y - pr.y * d.x);

        float wTap = baseW * sat(1.0 - along / max(1e-3, len));
        float m = step(0.0, along) * step(along, len) * step(perp, wTap);
        spike = max(spike, m);
    }

    float jewel = sat(1.0 - smoothstep(7.0, 9.0, r));

    // --- Letters: orbit positions rotate, glyph strokes stay upright ---
    float L = 13.0;
    float thick = 1.4;

    float letters = 0.0;

    vec2 posN = center + rot(vec2(0.0, -(R + 16.0)), ang);
    vec2 posS = center + rot(vec2(0.0,  (R + 16.0)), ang);
    vec2 posW = center + rot(vec2(-(R + 16.0), 0.0), ang);
    vec2 posE = center + rot(vec2( (R + 16.0), 0.0), ang);

    vec2 pN = fragPx - posN;
    letters = max(letters,
        segMask(pN, vec2(-L*0.45,  L*0.50), vec2(-L*0.45, -L*0.50), thick) +
        segMask(pN, vec2( L*0.45,  L*0.50), vec2( L*0.45, -L*0.50), thick) +
        segMask(pN, vec2(-L*0.45, -L*0.50), vec2( L*0.45,  L*0.50), thick)
    );

    vec2 pS = fragPx - posS;
    letters = max(letters,
        segMask(pS, vec2(-L*0.45, -L*0.50), vec2( L*0.45, -L*0.50), thick) +
        segMask(pS, vec2(-L*0.45,  0.0    ), vec2( L*0.45,  0.0    ), thick) +
        segMask(pS, vec2(-L*0.45,  L*0.50), vec2( L*0.45,  L*0.50), thick) +
        segMask(pS, vec2(-L*0.45, -L*0.50), vec2(-L*0.45,  0.0    ), thick) +
        segMask(pS, vec2( L*0.45,  0.0    ), vec2( L*0.45,  L*0.50), thick)
    );

    vec2 pW = fragPx - posW;
    letters = max(letters,
        segMask(pW, vec2(-L*0.50, -L*0.50), vec2(-L*0.35,  L*0.50), thick) +
        segMask(pW, vec2(-L*0.35,  L*0.50), vec2( 0.0,   -L*0.10), thick) +
        segMask(pW, vec2( 0.0,   -L*0.10), vec2( L*0.35,  L*0.50), thick) +
        segMask(pW, vec2( L*0.35,  L*0.50), vec2( L*0.50, -L*0.50), thick)
    );

    vec2 pE = fragPx - posE;
    letters = max(letters,
        segMask(pE, vec2(-L*0.45, -L*0.50), vec2(-L*0.45,  L*0.50), thick) +
        segMask(pE, vec2(-L*0.45, -L*0.50), vec2( L*0.45, -L*0.50), thick) +
        segMask(pE, vec2(-L*0.45,  0.0    ), vec2( L*0.25,  0.0    ), thick) +
        segMask(pE, vec2(-L*0.45,  L*0.50), vec2( L*0.45,  L*0.50), thick)
    );

    letters = sat(letters);

    // COLORS (Brighter)
    vec3 cRing = vec3(0.51, 0.84, 0.87); //vec3(0.78, 0.80, 0.82);
    vec3 cSpike = vec3(0.51, 0.84, 0.87); //vec3(0.40, 0.78, 0.76);
    vec3 cSpike2 = vec3(0.98, 0.74, 0.56); //vec3(0.92, 0.75, 0.55);
    vec3 cJewel = vec3(0.98, 0.80, 0.58);
    vec3 cLet = vec3(0.98, 0.80, 0.58); //vec3(0.80, 0.72, 0.65);

    // COLORS (subtle vintage)
    /*
    vec3 cRing  = vec3(0.78, 0.80, 0.82);
    vec3 cSpike = vec3(0.40, 0.78, 0.76);
    vec3 cSpike2= vec3(0.92, 0.75, 0.55);
    vec3 cJewel = vec3(0.98, 0.80, 0.58);
    vec3 cLet   = vec3(0.80, 0.72, 0.65);
    */

    float alt = 0.5 + 0.5 * sin(atan(pr.y, pr.x) * 8.0);
    vec3 spikeCol = mix(cSpike, cSpike2, alt);

    vec3 col = vec3(0.0);
    col += spikeCol * spike * 0.95;
    col += cRing * ring * 0.95;
    col += cRing * ring2 * 0.65;
    col = mix(col, cJewel, jewel);
    col = mix(col, cLet, letters);

    float alpha = sat(max(max(spike * 0.85, ring), max(ring2 * 0.6, max(jewel, letters))));
    float pulse = 0.90 + 0.10 * sin(t * 2.3);
    col *= pulse;

    return vec4(col, alpha * 1.0);
    //return vec4(col, alpha * 0.75);
}

void main()
{
    if (pc.a.w < 0.5)
    {
        outColor = vec4(0.0);
        return;
    }

    vec2 fragPx = gl_FragCoord.xy - vec2(0.5);

    vec4 fm  = drawFullMap(fragPx);
    vec4 lg  = drawLegend(fragPx);
    vec4 mh  = drawMouseHint(fragPx);
    vec4 cp  = drawCompassRose(fragPx);
    vec4 mm  = drawMinimap(fragPx);
    vec4 hud = drawHudPanel(fragPx);
    vec4 cr  = drawCrosshair(fragPx);

    float mapFade = sat(pc.c.w);
    cr.a *= (1.0 - mapFade);
    cp.a *= (0.95 - 0.25 * mapFade);

    vec4 accum = vec4(0.0);
    accum = overStraight(accum, fm);
    accum = overStraight(accum, lg);
    accum = overStraight(accum, mh);
    accum = overStraight(accum, cp);
    accum = overStraight(accum, mm);
    accum = overStraight(accum, hud);
    accum = overStraight(accum, cr);

    outColor = accum;
}
