/*
    Starship Raycaster - A GPU-accelerated raycasting demo built with SDL3 and Vulkan.
    Copyright (C) 2026 Walter W. Whitman aka The Joyful Programmer (tm)
    Copyright (C) 2026 AstroCosmic Systems (tm)
    Copyright (C) 2026 Mini Yorkies Software (tm)

    This software is provided 'as-is', without any express or implied
    warranty.  In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.

    2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.

    3. This notice may not be removed or altered from any source distribution.

    This project is my attempt to build a modern GPU-accelerated raycasting demo
    in the spirit of classic 90s "2.5D" shooters, with a single-deck ship map as
    the main game overlay. It's also a personal sandbox for learning Vulkan and
    SDL3, and a testbed for various palette-building and quantization techniques.

    The code is organized into a few main components:
    - main.cpp: SDL3 app entrypoint and event loop, forwarding to App.
    - starship_raycaster.hpp/cpp: The main application class, Vulkan setup,
        rendering loop, and game overlay logic.
    - star_shipgen.hpp/cpp: A BSP-based procedural ship map generator, producing
        a grid of "tiles" that the raycaster renders.
    - star_palette.hpp/cpp: CPU palette-building utilities, including a perceptual
        palette builder based on a GPU-accelerated histogram.

    The project is built with C++26, and uses the Vulkan graphics API for rendering
    and SDL3 for windowing and input. It should compile and run on Windows, Linux,
    and macOS (with Vulkan support).

    The code is licensed under the zlib License (see above), which allows for free
    use and modification with minimal restrictions. Attribution is appreciated but
    not required.

    The testbed of palette-building techniques is a key part of the project, and includes:
    - A GPU-accelerated histogram builder that computes a 33^3 color histogram of
      the rendered image.
    - A CPU palette builder that takes the histogram and produces a 256-color palette
      using a weighted median-cut algorithm.
    - Support for preset palettes (e.g. EGA/VGA) and various dithering algorithms
      (Floyd-Steinberg, Bayer matrix, etc.).
    - A final display pass that looks up palette indices to show the quantized image.
    
    The game overlay is a simple GPU raycaster that renders a 2D grid-based map of "tiles"
    into a 3D view. The map is generated by a BSP-based algorithm that creates rooms,
    corridors, and zones with different themes. The raycaster supports walls, doors,
    stairs, and sprites (for NPCs or decorations). The player can move around the map and
    interact with doors.
    
    The project is a work in progress and may contain rough edges or incomplete features.
    
    Enjoy exploring the code and the demo!
*/
#version 450
layout(location = 0) out vec4 outColor;

layout(push_constant) uniform Push
{
    vec4 a; // (w, h, timeSeconds, enabled)
    vec4 b; // (baseSizePx, health01, reserved, reserved)
    vec4 c;
    uvec4 d;
} pc;

float sat(float x) { return clamp(x, 0.0, 1.0); }

float smootherstep(float x)
{
    x = sat(x);
    return x * x * (3.0 - 2.0 * x);
}

void main()
{
    float w = pc.a.x;
    float h = pc.a.y;
    float t = pc.a.z;

    float baseSize = pc.b.x;
    float health01 = sat(pc.b.y);
    float severity = 1.0 - health01;

    if (pc.a.w < 0.5 || baseSize <= 0.5)
    {
        outColor = vec4(0.0);
        return;
    }

    float s = 0.5 + 0.5 * sin(t * 6.0);
    float effSize = baseSize * mix(0.88, 1.06, s);

    vec2 p = gl_FragCoord.xy - vec2(0.5);

    float dx = min(p.x, (w - 1.0) - p.x);
    float dy = min(p.y, (h - 1.0) - p.y);

    float side = sat((effSize - dx) / effSize);
    float topb = sat((effSize - dy) / effSize) * 0.65;

    float m = max(side, topb);
    m = smootherstep(m);

    float edgeA = m * mix(0.08, 0.58, pow(severity, 0.70)) * mix(0.85, 1.05, s);

    float dead = smootherstep(sat((0.02 - health01) / 0.02));
    float bgA = 0.26 * dead;

    vec3 edgeCol = mix(vec3(0.35, 0.05, 0.05), vec3(1.0, 0.0, 0.0), pow(severity, 0.65));
    vec3 deadCol = vec3(0.35, 0.02, 0.02);

    float a = sat(edgeA + bgA);
    vec3 prem = edgeCol * edgeA + deadCol * bgA;
    vec3 rgb = (a > 1e-6) ? (prem / a) : vec3(0.0);

    outColor = vec4(rgb, a);
}
