/*
    Starship Raycaster - A GPU-accelerated raycasting demo built with SDL3 and Vulkan.
    Copyright (C) 2026 Walter W. Whitman aka The Joyful Programmer (tm)
    Copyright (C) 2026 AstroCosmic Systems (tm)
    Copyright (C) 2026 Mini Yorkies Software (tm)

    This software is provided 'as-is', without any express or implied
    warranty.  In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.

    2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.

    3. This notice may not be removed or altered from any source distribution.

    This project is my attempt to build a modern GPU-accelerated raycasting demo
    in the spirit of classic 90s "2.5D" shooters, with a single-deck ship map as
    the main game overlay. It's also a personal sandbox for learning Vulkan and
    SDL3, and a testbed for various palette-building and quantization techniques.

    The code is organized into a few main components:
    - main.cpp: SDL3 app entrypoint and event loop, forwarding to App.
    - starship_raycaster.hpp/cpp: The main application class, Vulkan setup,
        rendering loop, and game overlay logic.
    - star_shipgen.hpp/cpp: A BSP-based procedural ship map generator, producing
        a grid of "tiles" that the raycaster renders.
    - star_palette.hpp/cpp: CPU palette-building utilities, including a perceptual
        palette builder based on a GPU-accelerated histogram.

    The project is built with C++26, and uses the Vulkan graphics API for rendering
    and SDL3 for windowing and input. It should compile and run on Windows, Linux,
    and macOS (with Vulkan support).

    The code is licensed under the zlib License (see above), which allows for free
    use and modification with minimal restrictions. Attribution is appreciated but
    not required.

    The testbed of palette-building techniques is a key part of the project, and includes:
    - A GPU-accelerated histogram builder that computes a 33^3 color histogram of
      the rendered image.
    - A CPU palette builder that takes the histogram and produces a 256-color palette
      using a weighted median-cut algorithm.
    - Support for preset palettes (e.g. EGA/VGA) and various dithering algorithms
      (Floyd-Steinberg, Bayer matrix, etc.).
    - A final display pass that looks up palette indices to show the quantized image.
    
    The game overlay is a simple GPU raycaster that renders a 2D grid-based map of "tiles"
    into a 3D view. The map is generated by a BSP-based algorithm that creates rooms,
    corridors, and zones with different themes. The raycaster supports walls, doors,
    stairs, and sprites (for NPCs or decorations). The player can move around the map and
    interact with doors.
    
    The project is a work in progress and may contain rough edges or incomplete features.
    
    Enjoy exploring the code and the demo!
*/
#version 450

layout(location = 0) out vec4 outColor;

layout(set = 0, binding = 0) uniform sampler2D uSrc;

layout(push_constant) uniform PresentPC
{
    vec2  rt;    // render target size (swapchain)
    float time;  // seconds
    uint  mode;  // 0..3 (re-using mapCrtMode_)
} pc;

float hash12(vec2 p)
{
    // cheap, deterministic noise
    float h = dot(p, vec2(127.1, 311.7));
    return fract(sin(h) * 43758.5453123);
}

vec3 sampleScene(vec2 uv)
{
    return texture(uSrc, uv).rgb;
}

vec3 crt(vec2 uv, float t, uint mode)
{
    vec2 p = uv * 2.0 - 1.0;
    float r2 = dot(p, p);

    // Barrel warp
    float k = 0.055;
    if (mode == 2u) k = 0.080;
    if (mode >= 3u) k = 0.115;
    p *= 1.0 + k * r2;

    vec2 duv = p * 0.5 + 0.5;

    // Soft edge falloff (avoid hard clamp pops)
    vec2 edge = smoothstep(vec2(0.0), vec2(0.02), duv) * (1.0 - smoothstep(vec2(0.98), vec2(1.0), duv));
    float edgeMask = edge.x * edge.y;

    duv = clamp(duv, 0.0, 1.0);

    vec3 col;

    // Chromatic offset (modes 2+)
    if (mode < 2u)
    {
        col = sampleScene(duv);
    }
    else
    {
        vec2 px = 1.0 / max(pc.rt, vec2(1.0));
        float chroma = (mode == 2u) ? 0.9 : 1.6;
        vec2 off = px * chroma * (0.5 + 0.75 * r2) * vec2(1.0, 0.55);

        float r = texture(uSrc, duv + off).r;
        float g = texture(uSrc, duv).g;
        float b = texture(uSrc, duv - off).b;
        col = vec3(r, g, b);
    }

    // Scanlines + subtle grille
    float y = duv.y * pc.rt.y;
    float x = duv.x * pc.rt.x;

    float scanAmp  = (mode >= 3u) ? 0.12 : 0.08;
    float grilleAmp = (mode >= 3u) ? 0.04 : 0.02;

    float scan   = 0.92 + scanAmp   * sin(y * 3.14159265);
    float grille = 0.98 + grilleAmp * sin(x * 3.14159265 * 0.5);

    col *= scan * grille;

    // Vignette
    vec2 v = uv - 0.5;
    float vig = 1.0 - dot(v, v) * 1.25;
    col *= clamp(vig, 0.0, 1.0);

    // Film grain
    float n = hash12(duv * pc.rt + t * vec2(23.17, 91.33));
    float grain = (n - 0.5);
    if (mode == 1u) grain *= 0.018;
    else if (mode == 2u) grain *= 0.024;
    else grain *= 0.030;
    col += grain;

    // Noise bloom pulse (mode 3)
    if (mode >= 3u)
    {
        float pulse = 0.5 + 0.5 * sin(t * 2.2);
        float luma = max(max(col.r, col.g), col.b);
        col += luma * (0.05 + 0.03 * pulse);

        // Slight horizontal jitter (classic CRT instability)
        float j = hash12(vec2(floor(y), t * 7.0)) - 0.5;
        float jitter = j * (0.0015 + 0.0025 * pulse);
        vec2 juv = clamp(vec2(duv.x + jitter, duv.y), 0.0, 1.0);
        col = mix(col, sampleScene(juv), 0.25);
    }

    // Fade at the warped borders
    col *= edgeMask;

    return col;
}

void main()
{
    vec2 uv = gl_FragCoord.xy / max(pc.rt, vec2(1.0));

    vec3 col = sampleScene(uv);

    if (pc.mode != 0u)
        col = crt(uv, pc.time, pc.mode);

    outColor = vec4(col, 1.0);
}
