/*
    Starship Raycaster - A GPU-accelerated raycasting demo built with SDL3 and Vulkan.
    Copyright (C) 2026 Walter W. Whitman aka The Joyful Programmer (tm)
    Copyright (C) 2026 AstroCosmic Systems (tm)
    Copyright (C) 2026 Mini Yorkies Software (tm)

    This software is provided 'as-is', without any express or implied
    warranty.  In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.

    2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.

    3. This notice may not be removed or altered from any source distribution.

    This project is my attempt to build a modern GPU-accelerated raycasting demo
    in the spirit of classic 90s "2.5D" shooters, with a single-deck ship map as
    the main game overlay. It's also a personal sandbox for learning Vulkan and
    SDL3, and a testbed for various palette-building and quantization techniques.

    The code is organized into a few main components:
    - main.cpp: SDL3 app entrypoint and event loop, forwarding to App.
    - starship_raycaster.hpp/cpp: The main application class, Vulkan setup,
        rendering loop, and game overlay logic.
    - star_shipgen.hpp/cpp: A BSP-based procedural ship map generator, producing
        a grid of "tiles" that the raycaster renders.
    - star_palette.hpp/cpp: CPU palette-building utilities, including a perceptual
        palette builder based on a GPU-accelerated histogram.

    The project is built with C++26, and uses the Vulkan graphics API for rendering
    and SDL3 for windowing and input. It should compile and run on Windows, Linux,
    and macOS (with Vulkan support).

    The code is licensed under the zlib License (see above), which allows for free
    use and modification with minimal restrictions. Attribution is appreciated but
    not required.

    The testbed of palette-building techniques is a key part of the project, and includes:
    - A GPU-accelerated histogram builder that computes a 33^3 color histogram of
      the rendered image.
    - A CPU palette builder that takes the histogram and produces a 256-color palette
      using a weighted median-cut algorithm.
    - Support for preset palettes (e.g. EGA/VGA) and various dithering algorithms
      (Floyd-Steinberg, Bayer matrix, etc.).
    - A final display pass that looks up palette indices to show the quantized image.
    
    The game overlay is a simple GPU raycaster that renders a 2D grid-based map of "tiles"
    into a 3D view. The map is generated by a BSP-based algorithm that creates rooms,
    corridors, and zones with different themes. The raycaster supports walls, doors,
    stairs, and sprites (for NPCs or decorations). The player can move around the map and
    interact with doors.
    
    The project is a work in progress and may contain rough edges or incomplete features.
    
    Enjoy exploring the code and the demo!
*/
#include "starship_raycaster.hpp"

#define SDL_MAIN_USE_CALLBACKS 1
#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>

#include <new>      // std::nothrow
#include <string>

struct AppState
{
    SDL_Window*         win = nullptr;
    Starship_Raycaster::App*   app = nullptr;
};

// SDL3 callback entrypoints use the C ABI.
// Letting a C++ exception escape through them is undefined behavior and can
// look like a "segmentation fault".
// We catch at the boundary and convert to SDL_Log + a clean shutdown.

// This function runs once at startup.
extern "C" SDL_AppResult SDL_AppInit(void** appstate, int /*argc*/, char* /*argv*/[])
{

    try
    {
        if (appstate) *appstate = nullptr;

        if (!SDL_Init(SDL_INIT_VIDEO))
        {
            SDL_Log("SDL_Init failed: %s", SDL_GetError());
            return SDL_APP_FAILURE;
        }

        SDL_Window* win = SDL_CreateWindow(
            "Starship Raycaster",
            1280, 720,
            SDL_WINDOW_VULKAN | SDL_WINDOW_RESIZABLE
        );

        if (!win)
        {
            SDL_Log("SDL_CreateWindow failed: %s", SDL_GetError());
            return SDL_APP_FAILURE;
        }

        // Mouse capture is managed by the App (TAB to release, click to recapture).

        auto* st = new (std::nothrow) AppState{};
        if (!st)
        {
            SDL_Log("Out of memory allocating AppState.");
            SDL_DestroyWindow(win);
            return SDL_APP_FAILURE;
        }

        st->win = win;

        // Set early so the catch block can clean up reliably.
        if (appstate) *appstate = st;

        // NOTE: App constructor may throw (Vulkan init, shader loads, etc.)
        // Do NOT allow it to cross the C ABI boundary.
        st->app = new Starship_Raycaster::App(st->win);

        return SDL_APP_CONTINUE;
    }
    catch (const std::exception& e)
    {
        SDL_Log("Fatal error during init: %s", e.what());
        // Best-effort cleanup.
        if (appstate && *appstate)
        {
            auto* st = static_cast<AppState*>(*appstate);
            delete st->app;
            st->app = nullptr;
            if (st->win) SDL_DestroyWindow(st->win);
            delete st;
            *appstate = nullptr;
        }
        SDL_Quit();
        return SDL_APP_FAILURE;
    }
    catch (...)
    {
        SDL_Log("Fatal error during init: unknown exception");
        SDL_Quit();
        return SDL_APP_FAILURE;
    }
}

// This function runs when a new event occurs.
extern "C" SDL_AppResult SDL_AppEvent(void* appstate, SDL_Event* event)
{
    try
    {
        auto* st = static_cast<AppState*>(appstate);
        if (!st || !event) return SDL_APP_FAILURE;

        switch (event->type)
        {
            case SDL_EVENT_QUIT:
                return SDL_APP_SUCCESS;

            case SDL_EVENT_KEY_DOWN:
                if (st->app) st->app->onKeyDown(event->key.key, event->key.mod);
                return SDL_APP_CONTINUE;

            case SDL_EVENT_MOUSE_MOTION:
                if (st->app) st->app->onMouseMotion((float)event->motion.x, (float)event->motion.y, (float)event->motion.xrel, (float)event->motion.yrel);
                return SDL_APP_CONTINUE;

            case SDL_EVENT_MOUSE_WHEEL:
            {
                if (!st->app) return SDL_APP_CONTINUE;
                float mx = 0.0f, my = 0.0f;
                SDL_GetMouseState(&mx, &my);
                // SDL3: SDL_MouseWheelEvent does not provide modifier keys.
                // Query the current state at the time of the event.
                SDL_Keymod mods = SDL_GetModState();
                st->app->onMouseWheel((float)event->wheel.y, mods, mx, my);
                return SDL_APP_CONTINUE;
            }

            case SDL_EVENT_MOUSE_BUTTON_DOWN:
                if (st->app) st->app->onMouseButtonDown(event->button.button);
                return SDL_APP_CONTINUE;

            case SDL_EVENT_WINDOW_FOCUS_LOST:
                if (st->app) st->app->onWindowFocusLost();
                return SDL_APP_CONTINUE;

            // HiDPI / resize correctness: recreate when pixel size changes.
            // Bonus: draw immediately so live-resize doesn't show black gaps.
            case SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED:
            {
                if (!st->app) return SDL_APP_CONTINUE;
                int w=0, h=0;
                SDL_GetWindowSizeInPixels(st->win, &w, &h);
                if (w > 0 && h > 0)
                    st->app->onFramebufferResize((uint32_t)w, (uint32_t)h);
                st->app->drawFrame();
                return SDL_APP_CONTINUE;
            }

            default:
                return SDL_APP_CONTINUE;
        }
    }
    catch (const std::exception& e)
    {
        SDL_Log("Fatal error during event handling: %s", e.what());
        return SDL_APP_FAILURE;
    }
    catch (...)
    {
        SDL_Log("Fatal error during event handling: unknown exception");
        return SDL_APP_FAILURE;
    }
}

// This function runs once per iteration and is the heart of the program.
extern "C" SDL_AppResult SDL_AppIterate(void* appstate)
{
    try
    {
        auto* st = static_cast<AppState*>(appstate);
        if (!st || !st->app) return SDL_APP_FAILURE;

        st->app->drawFrame();
        return SDL_APP_CONTINUE;
    }
    catch (const std::exception& e)
    {
        SDL_Log("Fatal error during frame: %s", e.what());
        return SDL_APP_FAILURE;
    }
    catch (...)
    {
        SDL_Log("Fatal error during frame: unknown exception");
        return SDL_APP_FAILURE;
    }
}

// This function runs once at shutdown.
extern "C" void SDL_AppQuit(void* appstate, SDL_AppResult /*result*/)
{
    auto* st = static_cast<AppState*>(appstate);
    if (!st) return;

    delete st->app;
    st->app = nullptr;

    if (st->win)
    {
        SDL_DestroyWindow(st->win);
        st->win = nullptr;
    }

    delete st;
}
