/*
    Starship Raycaster - A GPU-accelerated raycasting demo built with SDL3 and Vulkan.
    Copyright (C) 2026 Walter W. Whitman aka The Joyful Programmer (tm)
    Copyright (C) 2026 AstroCosmic Systems (tm)
    Copyright (C) 2026 Mini Yorkies Software (tm)

    This software is provided 'as-is', without any express or implied
    warranty.  In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.

    2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.

    3. This notice may not be removed or altered from any source distribution.

    This project is my attempt to build a modern GPU-accelerated raycasting demo
    in the spirit of classic 90s "2.5D" shooters, with a single-deck ship map as
    the main game overlay. It's also a personal sandbox for learning Vulkan and
    SDL3, and a testbed for various palette-building and quantization techniques.

    The code is organized into a few main components:
    - main.cpp: SDL3 app entrypoint and event loop, forwarding to App.
    - starship_raycaster.hpp/cpp: The main application class, Vulkan setup,
        rendering loop, and game overlay logic.
    - star_shipgen.hpp/cpp: A BSP-based procedural ship map generator, producing
        a grid of "tiles" that the raycaster renders.
    - star_palette.hpp/cpp: CPU palette-building utilities, including a perceptual
        palette builder based on a GPU-accelerated histogram.

    The project is built with C++26, and uses the Vulkan graphics API for rendering
    and SDL3 for windowing and input. It should compile and run on Windows, Linux,
    and macOS (with Vulkan support).

    The code is licensed under the zlib License (see above), which allows for free
    use and modification with minimal restrictions. Attribution is appreciated but
    not required.

    The testbed of palette-building techniques is a key part of the project, and includes:
    - A GPU-accelerated histogram builder that computes a 33^3 color histogram of
      the rendered image.
    - A CPU palette builder that takes the histogram and produces a 256-color palette
      using a weighted median-cut algorithm.
    - Support for preset palettes (e.g. EGA/VGA) and various dithering algorithms
      (Floyd-Steinberg, Bayer matrix, etc.).
    - A final display pass that looks up palette indices to show the quantized image.
    
    The game overlay is a simple GPU raycaster that renders a 2D grid-based map of "tiles"
    into a 3D view. The map is generated by a BSP-based algorithm that creates rooms,
    corridors, and zones with different themes. The raycaster supports walls, doors,
    stairs, and sprites (for NPCs or decorations). The player can move around the map and
    interact with doors.
    
    The project is a work in progress and may contain rough edges or incomplete features.
    
    Enjoy exploring the code and the demo!
*/
#include "star_palette.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <vector>

namespace star::pal
{
    // --- small helpers ---
    static inline float clampf(float v, float a, float b) { return v < a ? a : (v > b ? b : v); }

    // Returns HSV with H in [0,360), S,V in [0,1]
    static inline void rgbToHsv(const RGB8& c, float& h, float& s, float& v)
    {
        const float r = c.r / 255.0f;
        const float g = c.g / 255.0f;
        const float b = c.b / 255.0f;

        const float mx = std::max({r,g,b});
        const float mn = std::min({r,g,b});
        const float d = mx - mn;

        v = mx;
        s = (mx <= 0.0f) ? 0.0f : (d / mx);

        if (d <= 0.0f) { h = 0.0f; return; }

        if (mx == r)      h = 60.0f * std::fmod(((g - b) / d), 6.0f);
        else if (mx == g) h = 60.0f * (((b - r) / d) + 2.0f);
        else              h = 60.0f * (((r - g) / d) + 4.0f);

        if (h < 0.0f) h += 360.0f;
    }

    static inline RGB8 hsvToRgb(float h, float s, float v)
    {
        h = std::fmod(h, 360.0f);
        if (h < 0.0f) h += 360.0f;

        const float c = v * s;
        const float x = c * (1.0f - std::fabs(std::fmod(h / 60.0f, 2.0f) - 1.0f));
        const float m = v - c;

        float rr=0, gg=0, bb=0;
        if      (h < 60)  { rr=c; gg=x; bb=0; }
        else if (h < 120) { rr=x; gg=c; bb=0; }
        else if (h < 180) { rr=0; gg=c; bb=x; }
        else if (h < 240) { rr=0; gg=x; bb=c; }
        else if (h < 300) { rr=x; gg=0; bb=c; }
        else              { rr=c; gg=0; bb=x; }

        RGB8 out;
        out.r = (uint8_t)std::lround(clampf((rr + m) * 255.0f, 0.0f, 255.0f));
        out.g = (uint8_t)std::lround(clampf((gg + m) * 255.0f, 0.0f, 255.0f));
        out.b = (uint8_t)std::lround(clampf((bb + m) * 255.0f, 0.0f, 255.0f));
        return out;
    }

    static inline uint32_t dist2Weighted(const RGB8& a, const RGB8& b)
    {
        const int dr = int(a.r) - int(b.r);
        const int dg = int(a.g) - int(b.g);
        const int db = int(a.b) - int(b.b);
        return uint32_t(30*dr*dr + 59*dg*dg + 11*db*db);
    }

    static inline float wrapHue(float h)
    {
        h = std::fmod(h, 360.0f);
        if (h < 0.0f) h += 360.0f;
        return h;
    }

    // Return 16 hue values (degrees) that feed the 16x16 color-theory palette.
    // We treat the palette as 16 "hue bands" (hi=0..15), each band having 16
    // luminance/saturation variations (li=0..15).
    //
    // This is intentionally simple and deterministic:
    // - choose a small set of distinct hues for the scheme
    // - repeat them across 16 bands
    static inline std::array<float, 16> schemeHues(float baseHueDeg, ColorTheoryScheme scheme)
    {
        std::vector<float> offsets;
        offsets.reserve(8);

        switch (scheme)
        {
            default:
            case ColorTheoryScheme::Monochromatic:
                offsets = { 0.0f };
                break;

            case ColorTheoryScheme::SplitComplementary:
                // base, complement-30, complement+30
                offsets = { 0.0f, 150.0f, 210.0f };
                break;

            case ColorTheoryScheme::Triadic:
                offsets = { 0.0f, 120.0f, 240.0f };
                break;

            case ColorTheoryScheme::Analogous:
                // Tight cluster around base
                offsets = { -60.0f, -30.0f, 0.0f, 30.0f, 60.0f };
                break;

            case ColorTheoryScheme::Diad:
                // Complementary pair (two-color harmony)
                offsets = { 0.0f, 180.0f };
                break;

            case ColorTheoryScheme::Square:
                offsets = { 0.0f, 90.0f, 180.0f, 270.0f };
                break;

            case ColorTheoryScheme::Tetradic:
                // Rectangle (two complementary pairs)
                offsets = { 0.0f, 60.0f, 180.0f, 240.0f };
                break;
        }

        std::array<float,16> out{};
        const int n = (int)offsets.size();
        for (int i = 0; i < 16; ++i)
        {
            out[i] = wrapHue(baseHueDeg + offsets[i % n]);
        }
        return out;
    }

    std::array<RGB8, 256> buildGradient(RGB8 a, RGB8 b)
    {
        std::array<RGB8,256> out{};
        for (int i=0;i<256;++i)
        {
            const float t = float(i)/255.0f;
            out[i].r = (uint8_t)std::lround(a.r + (b.r - a.r)*t);
            out[i].g = (uint8_t)std::lround(a.g + (b.g - a.g)*t);
            out[i].b = (uint8_t)std::lround(a.b + (b.b - a.b)*t);
        }
        return out;
    }

    std::array<RGB8, 256> buildGradientN(RGB8 a, RGB8 b, uint32_t colorsToUse)
    {
        std::array<RGB8,256> out{};
        colorsToUse = std::max(2u, std::min(256u, colorsToUse));
        const uint32_t last = colorsToUse - 1u;
        for (uint32_t i=0; i<colorsToUse; ++i)
        {
            const float t = (colorsToUse <= 1u) ? 0.0f : float(i) / float(last);
            out[i].r = (uint8_t)std::lround(a.r + (b.r - a.r)*t);
            out[i].g = (uint8_t)std::lround(a.g + (b.g - a.g)*t);
            out[i].b = (uint8_t)std::lround(a.b + (b.b - a.b)*t);
        }
        for (uint32_t i=colorsToUse; i<256u; ++i) out[i] = out[last];
        return out;
    }
    // EGA/VGA-ish palette generation.
    // We generate the classic 16-color EGA block + 6x6x6 color cube + grayscale ramp.
    // (Many references describe this as "VGA default 256", and it's the same palette
    // you often see in old 256-color software renderers.)
    std::array<RGB8, 256> buildVga256()
    {
        // VGA standard 256-color palette, generated algorithmically from a known DAC table pattern
        // (originally popularized by the vgapal tool). It uses 6-bit DAC channels (0..63).
        //
        // Layout:
        //   0..15   : 16-color base (EGA-like, with "brown" exception)
        //   16..31  : 16 grays
        //   32..247 : 9 RGB cycles * 24 colors each (216)
        //   248..255: 8 blacks
        //
        // 6-bit -> 8-bit expansion: (v<<2) | (v>>4)
        std::array<RGB8,256> out{};
        uint32_t idx = 0;

        auto levelUp = [](int n6)->uint8_t {
            return (uint8_t)((n6<<2) | (n6>>4));
        };

        auto addColor6 = [&](int r6, int g6, int b6)
        {
            if (idx >= 256) return;
            out[idx++] = RGB8{ levelUp(r6), levelUp(g6), levelUp(b6) };
        };

        auto add16Color = [&](int lo, int melo, int mehi, int hi)
        {
            for (int i=0;i<8;++i)
            {
                int r=lo, g=lo, b=lo;
                if (i & 4) r = mehi;
                if (i & 2) g = (i==6) ? melo : mehi; // exception: color 6 is brown
                if (i & 1) b = mehi;
                addColor6(r,g,b);
            }
            for (int i=0;i<8;++i)
            {
                int r=melo, g=melo, b=melo;
                if (i & 4) r = hi;
                if (i & 2) g = hi;
                if (i & 1) b = hi;
                addColor6(r,g,b);
            }
        };

        auto addGrayColor = [&](int v6){ addColor6(v6,v6,v6); };

        auto addRun = [&](int start, int ch, int lo, int melo, int me, int mehi, int hi)
        {
            int r=lo, g=lo, b=lo;
            if (start & 4) r = hi;
            if (start & 2) g = hi;
            if (start & 1) b = hi;
            addColor6(r,g,b);

            const bool up = (start & ch) != ch; // channel starts low -> going up
            auto setCh = [&](int v){
                if (ch==4) r=v;
                else if (ch==2) g=v;
                else b=v;
            };

            setCh(up ? melo : mehi); addColor6(r,g,b);
            setCh(me);              addColor6(r,g,b);
            setCh(up ? mehi : melo); addColor6(r,g,b);
        };

        auto addCycle = [&](int lo, int melo, int me, int mehi, int hi)
        {
            int hue = 1; // blue
            addRun(hue, 4, lo, melo, me, mehi, hi);
            hue ^= 4; // 5
            addRun(hue, 1, lo, melo, me, mehi, hi);
            hue ^= 1; // 4
            addRun(hue, 2, lo, melo, me, mehi, hi);
            hue ^= 2; // 6
            addRun(hue, 4, lo, melo, me, mehi, hi);
            hue ^= 4; // 2
            addRun(hue, 1, lo, melo, me, mehi, hi);
            hue ^= 1; // 3
            addRun(hue, 2, lo, melo, me, mehi, hi);
        };

        add16Color(0, 21, 42, 63);

        // 16 grays (6-bit)
        const int grays[16] = {0,5,8,11,14,17,20,24,28,32,36,40,45,50,56,63};
        for (int g: grays) addGrayColor(g);

        // Nine RGB cycles in three groups (value/saturation)
        addCycle( 0, 16, 31, 47, 63);
        addCycle(31, 39, 47, 55, 63);
        addCycle(45, 49, 54, 58, 63);

        addCycle( 0,  7, 14, 21, 28);
        addCycle(14, 17, 21, 24, 28);
        addCycle(20, 22, 24, 26, 28);

        addCycle( 0,  4,  8, 12, 16);
        addCycle( 8, 10, 12, 14, 16);
        addCycle(11, 12, 13, 15, 16);

        // Final eight entries are black
        for (int i=0;i<8;++i) addGrayColor(0);

        // Safety pad
        while (idx < 256) addGrayColor(0);

        return out;
    }

std::array<RGB8, 256> buildColorTheory(uint8_t hue, uint8_t luminance, ColorTheoryScheme scheme)
    {
        std::array<RGB8,256> out{};
        const float baseH = (float(hue) / 255.0f) * 360.0f;

        auto hues = schemeHues(baseH, scheme);

        // Luminance control: center around user's luminance, but span full 0..1 range.
        const float L = float(luminance) / 255.0f;

        // 16 luminance steps, biased around L but reaching to black/white.
        for (int hi=0; hi<16; ++hi)
        {
            for (int li=0; li<16; ++li)
            {
                const float t = float(li)/15.0f;
                // Blend between black -> L -> white
                float v = (t < 0.5f) ? (L * (t/0.5f)) : (L + (1.0f-L)*((t-0.5f)/0.5f));

                // Saturation: higher in mid-range, lower near extremes
                float s = 1.0f - std::fabs(t-0.5f)*1.6f;
                s = clampf(s, 0.05f, 1.0f);

                out[hi*16 + li] = hsvToRgb(hues[hi], s, v);
            }
        }
        return out;
    }

    std::array<RGB8, 256> buildColorTheoryN(uint8_t hue, uint8_t luminance, ColorTheoryScheme scheme, uint32_t colorsToUse)
    {
        colorsToUse = std::max(2u, std::min(256u, colorsToUse));
        auto full = buildColorTheory(hue, luminance, scheme);
        if (colorsToUse >= 256u) return full;

        std::array<RGB8,256> out{};
        const uint32_t last = colorsToUse - 1u;
        for (uint32_t i=0; i<colorsToUse; ++i)
        {
            const float t = (last == 0u) ? 0.0f : float(i) / float(last);
            const uint32_t src = (uint32_t)std::lround(t * 255.0f);
            out[i] = full[src];
        }
        for (uint32_t i=colorsToUse; i<256u; ++i)
            out[i] = out[last];
        return out;
    }


    std::array<RGB8, 256> buildPerceptualPalette(const uint8_t* rgba, int w, int h)
    {
        // Port of the QB64 BASIC routine:
        // - sample the image in a 64x64-ish grid
        // - collect up to 4096 unique colors with counts
        // - pick the most-popular as seed
        // - iteratively add the color that maximizes (minDist^2 * (count/maxCount))
        // - finally sort chosen colors by hue then brightness

        struct Item { RGB8 c; int count; bool used; };

        const int maxUnique = 4096;
        std::vector<Item> colors;
        colors.reserve(maxUnique);

        const int stepX = std::max(1, w / 64);
        const int stepY = std::max(1, h / 64);

        for (int y=0; y<h; y+=stepY)
        {
            for (int x=0; x<w; x+=stepX)
            {
                const size_t i = (size_t(y)*size_t(w) + size_t(x)) * 4;
                RGB8 c{rgba[i+0], rgba[i+1], rgba[i+2]};

                // exact match search (unique <= 4096, so linear is OK here)
                bool found = false;
                for (auto& it : colors)
                {
                    if (it.c.r==c.r && it.c.g==c.g && it.c.b==c.b)
                    {
                        it.count++;
                        found = true;
                        break;
                    }
                }
                if (!found)
                {
                    if ((int)colors.size() >= maxUnique) continue;
                    colors.push_back(Item{c, 1, false});
                }
            }
        }

        std::array<RGB8,256> out{};
        if (colors.empty())
        {
            // fallback: grayscale
            return buildGradient(RGB8{0,0,0}, RGB8{255,255,255});
        }

        int maxCount = 1;
        for (auto& it : colors) maxCount = std::max(maxCount, it.count);

        // Seed: most popular
        int best = 0;
        for (int i=1;i<(int)colors.size();++i)
            if (colors[i].count > colors[best].count) best = i;

        std::array<RGB8,256> chosen{};
        chosen[0] = colors[best].c;
        colors[best].used = true;

        // Farthest-point sampling with popularity factor
        for (int k=1; k<256; ++k)
        {
            float bestScore = -1.0f;
            int bestIdx = best;

            for (int i=0;i<(int)colors.size();++i)
            {
                if (colors[i].used) continue;

                uint32_t minD = 0xFFFFFFFFu;
                for (int j=0;j<k;++j)
                    minD = std::min(minD, dist2Weighted(colors[i].c, chosen[j]));

                const float pop = float(colors[i].count) / float(maxCount);
                const float score = float(minD) * pop;

                if (score > bestScore)
                {
                    bestScore = score;
                    bestIdx = i;
                }
            }

            chosen[k] = colors[bestIdx].c;
            colors[bestIdx].used = true;
        }

        // Sort by hue then brightness (value)
        struct SortItem { RGB8 c; float h,s,v; };
        std::array<SortItem,256> srt{};
        for (int i=0;i<256;++i)
        {
            float h0,s0,v0;
            rgbToHsv(chosen[i], h0,s0,v0);
            srt[i] = SortItem{chosen[i], h0,s0,v0};
        }

        std::sort(srt.begin(), srt.end(), [](const SortItem& a, const SortItem& b){
            if (a.h != b.h) return a.h < b.h;
            return a.v < b.v;
        });

        for (int i=0;i<256;++i) out[i] = srt[i].c;
        return out;
    }


    std::array<RGB8,256> buildPerceptualPaletteFromHistogram33(const uint32_t* histogram33, uint32_t colorsToUse)
    {
        colorsToUse = std::max(2u, std::min(256u, colorsToUse));

        // Fallback if no histogram available.
        if (!histogram33)
        {
            return buildGradient(RGB8{0,0,0}, RGB8{255,255,255});
        }

        struct Item { RGB8 c; uint32_t count; };
        constexpr size_t N = 33u;
        constexpr size_t MAX_UNIQUE = 4096u;

        std::vector<Item> items;
        items.reserve(4096);

        // Expand the 33^3 bins into a list of unique colors with weights.
        // The GPU histogram is already based on a sampled grid, so this is cheap enough.
        for (uint32_t r = 0; r < N; ++r)
        for (uint32_t g = 0; g < N; ++g)
        for (uint32_t b = 0; b < N; ++b)
        {
            const uint32_t idx = uint32_t((r*N + g)*N + b);
            const uint32_t cnt = histogram33[idx];
            if (!cnt) continue;

            RGB8 c{
                (uint8_t)std::lround(float(r) * 255.0f / float(N - 1)),
                (uint8_t)std::lround(float(g) * 255.0f / float(N - 1)),
                (uint8_t)std::lround(float(b) * 255.0f / float(N - 1))
            };
            items.push_back(Item{c, cnt});
        }

        if (items.empty())
        {
            return buildGradient(RGB8{0,0,0}, RGB8{255,255,255});
        }

        // Keep only the top MAX_UNIQUE bins by count (avoids quadratic blow-ups).
        if (items.size() > MAX_UNIQUE)
        {
            std::nth_element(items.begin(), items.begin() + (ptrdiff_t)MAX_UNIQUE, items.end(),
                [](const Item& a, const Item& b){ return a.count > b.count; });
            items.resize(MAX_UNIQUE);
        }

        uint32_t maxCount = 1;
        for (const auto& it : items) maxCount = std::max(maxCount, it.count);

        // Seed: most popular color.
        size_t seed = 0;
        for (size_t i = 1; i < items.size(); ++i)
            if (items[i].count > items[seed].count) seed = i;

        std::array<RGB8,256> chosen{};
        std::vector<uint32_t> minDist(items.size(), 0xFFFFFFFFu);
        std::vector<uint8_t> used(items.size(), 0u);

        chosen[0] = items[seed].c;
        used[seed] = 1u;

        for (size_t i = 0; i < items.size(); ++i)
        {
            if (used[i]) continue;
            minDist[i] = dist2Weighted(items[i].c, chosen[0]);
        }

        // Farthest-point sampling with popularity factor, but O(N*K) via incremental minDist updates.
        for (uint32_t k = 1; k < colorsToUse; ++k)
        {
            float bestScore = -1.0f;
            size_t bestIdx = seed;

            for (size_t i = 0; i < items.size(); ++i)
            {
                if (used[i]) continue;
                const float pop = float(items[i].count) / float(maxCount);
                const float score = float(minDist[i]) * pop;
                if (score > bestScore)
                {
                    bestScore = score;
                    bestIdx = i;
                }
            }

            chosen[k] = items[bestIdx].c;
            used[bestIdx] = 1u;

            for (size_t i = 0; i < items.size(); ++i)
            {
                if (used[i]) continue;
                minDist[i] = std::min(minDist[i], dist2Weighted(items[i].c, chosen[k]));
            }
        }

        // Sort chosen colors by hue then brightness (value), like the QB64 routine.
        struct SortItem { RGB8 c; float h,s,v; };
        std::vector<SortItem> srt;
        srt.reserve(colorsToUse);
        for (uint32_t i = 0; i < colorsToUse; ++i)
        {
            float h0,s0,v0;
            rgbToHsv(chosen[i], h0,s0,v0);
            srt.push_back(SortItem{chosen[i], h0,s0,v0});
        }

        std::sort(srt.begin(), srt.end(), [](const SortItem& a, const SortItem& b){
            if (a.h != b.h) return a.h < b.h;
            return a.v < b.v;
        });

        std::array<RGB8,256> out{};
        for (uint32_t i = 0; i < colorsToUse; ++i) out[i] = srt[i].c;
        for (uint32_t i = colorsToUse; i < 256u; ++i) out[i] = out[colorsToUse - 1];
        return out;
    }

    std::vector<uint32_t> buildLut33(const std::array<RGB8,256>& palIn, uint32_t colorsToUse)
    {
        colorsToUse = std::max(2u, std::min(256u, colorsToUse));
        const uint32_t N = 33u;
        std::vector<uint32_t> lut(N*N*N, 0u);

        auto sampleCoord = [&](uint32_t i)->RGB8{
            // map i in [0,32] to [0,255]
            uint8_t v = (uint8_t)std::lround(float(i) * 255.0f / float(N-1));
            return RGB8{v,v,v};
        };

        for (uint32_t r=0;r<N;++r)
        for (uint32_t g=0;g<N;++g)
        for (uint32_t b=0;b<N;++b)
        {
            RGB8 c{
                (uint8_t)std::lround(float(r)*255.0f/float(N-1)),
                (uint8_t)std::lround(float(g)*255.0f/float(N-1)),
                (uint8_t)std::lround(float(b)*255.0f/float(N-1))
            };

            uint32_t best = 0;
            uint32_t bestD = 0xFFFFFFFFu;
            for (uint32_t i=0;i<colorsToUse;++i)
            {
                uint32_t d = dist2Weighted(c, palIn[i]);
                if (d < bestD) { bestD = d; best = i; }
            }
            lut[(r*N + g)*N + b] = best;
        }

        return lut;
    }
}
