/*
    Starship Raycaster - A GPU-accelerated raycasting demo built with SDL3 and Vulkan.
    Copyright (C) 2026 Walter W. Whitman aka The Joyful Programmer (tm)
    Copyright (C) 2026 AstroCosmic Systems (tm)
    Copyright (C) 2026 Mini Yorkies Software (tm)

    This software is provided 'as-is', without any express or implied
    warranty.  In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.

    2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.

    3. This notice may not be removed or altered from any source distribution.

    This project is my attempt to build a modern GPU-accelerated raycasting demo
    in the spirit of classic 90s "2.5D" shooters, with a single-deck ship map as
    the main game overlay. It's also a personal sandbox for learning Vulkan and
    SDL3, and a testbed for various palette-building and quantization techniques.

    The code is organized into a few main components:
    - main.cpp: SDL3 app entrypoint and event loop, forwarding to App.
    - starship_raycaster.hpp/cpp: The main application class, Vulkan setup,
        rendering loop, and game overlay logic.
    - star_shipgen.hpp/cpp: A BSP-based procedural ship map generator, producing
        a grid of "tiles" that the raycaster renders.
    - star_palette.hpp/cpp: CPU palette-building utilities, including a perceptual
        palette builder based on a GPU-accelerated histogram.

    The project is built with C++26, and uses the Vulkan graphics API for rendering
    and SDL3 for windowing and input. It should compile and run on Windows, Linux,
    and macOS (with Vulkan support).

    The code is licensed under the zlib License (see above), which allows for free
    use and modification with minimal restrictions. Attribution is appreciated but
    not required.

    The testbed of palette-building techniques is a key part of the project, and includes:
    - A GPU-accelerated histogram builder that computes a 33^3 color histogram of
      the rendered image.
    - A CPU palette builder that takes the histogram and produces a 256-color palette
      using a weighted median-cut algorithm.
    - Support for preset palettes (e.g. EGA/VGA) and various dithering algorithms
      (Floyd-Steinberg, Bayer matrix, etc.).
    - A final display pass that looks up palette indices to show the quantized image.
    
    The game overlay is a simple GPU raycaster that renders a 2D grid-based map of "tiles"
    into a 3D view. The map is generated by a BSP-based algorithm that creates rooms,
    corridors, and zones with different themes. The raycaster supports walls, doors,
    stairs, and sprites (for NPCs or decorations). The player can move around the map and
    interact with doors.
    
    The project is a work in progress and may contain rough edges or incomplete features.
    
    Enjoy exploring the code and the demo!
*/
#include "star_shipgen.hpp"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <random>
#include <vector>

namespace Starship_Raycaster::shipgen
{
namespace
{
    // Must match App::TileType.
    enum : uint8_t
    {
        TILE_EMPTY      = 0,
        TILE_BRICK      = 1,
        TILE_METAL      = 2,
        TILE_GLASS      = 3,
        TILE_DOOR       = 4,
        TILE_STAIRS_UP  = 5,
        TILE_STAIRS_DOWN= 6,
    };

    // Zones (kept compatible with the demo's existing floor/ceiling palette mapping).
    enum : uint8_t
    {
        Z_NONE     = 0,
        Z_QUARTERS = 1,
        Z_LABS     = 2,
        Z_BRIG     = 3,
        Z_STORAGE  = 4,
        Z_DINING   = 5,
        Z_GARDENS  = 6,
        Z_THEATER  = 7,
        Z_REC      = 8,
        Z_BRIDGE   = 9,
        Z_CORRIDOR = 200,
    };

    inline uint32_t packCell(uint8_t t, uint8_t meta, bool locked, uint8_t zone)
    {
        // bits: [0..7]=type, [8..15]=doorOpen (or variant), [16]=locked, [17..24]=zone
        return uint32_t(t)
             | (uint32_t(meta) << 8)
             | (locked ? (1u << 16) : 0u)
             | (uint32_t(zone) << 17);
    }

    inline uint32_t idx(int x, int y, int w)
    {
        return uint32_t(y) * uint32_t(w) + uint32_t(x);
    }

    struct Rect
    {
        int x0=0, y0=0, x1=0, y1=0;
        int w() const { return x1 - x0 + 1; }
        int h() const { return y1 - y0 + 1; }
    };

    struct MapWriter
    {
        int W=0, H=0;
        std::vector<uint32_t>* cells=nullptr;
        std::vector<uint32_t> doorCells;

        uint32_t& at(int x, int y) { return (*cells)[idx(x,y,W)]; }

        void set(int x, int y, uint8_t t, uint8_t zone, uint8_t meta=0, bool locked=false)
        {
            if (x < 0 || y < 0 || x >= W || y >= H) return;
            const uint32_t i = idx(x,y,W);
            (*cells)[i] = packCell(t, meta, locked, zone);
            if (t == TILE_DOOR)
                doorCells.push_back(i);
        }

        void fillRect(int x0, int y0, int x1, int y1, uint8_t t, uint8_t zone, uint8_t meta=0, bool locked=false)
        {
            if (x0 > x1) std::swap(x0,x1);
            if (y0 > y1) std::swap(y0,y1);
            x0 = std::max(x0, 0); y0 = std::max(y0, 0);
            x1 = std::min(x1, W-1); y1 = std::min(y1, H-1);
            for (int y=y0; y<=y1; ++y)
                for (int x=x0; x<=x1; ++x)
                    set(x,y,t,zone,meta,locked);
        }

        void carveRoom(const Rect& r, uint8_t wall, uint8_t zone)
        {
            for (int y=r.y0; y<=r.y1; ++y)
            {
                for (int x=r.x0; x<=r.x1; ++x)
                {
                    const bool edge = (x==r.x0 || x==r.x1 || y==r.y0 || y==r.y1);
                    set(x,y, edge ? wall : TILE_EMPTY, zone);
                }
            }
        }

        // frontSide: -1 none, 0 left wall, 1 right wall
        void addFrontDoorAndWindows(const Rect& r, int frontSide, uint8_t zone)
        {
            if (frontSide != 0 && frontSide != 1) return;

            const int doorX = (frontSide==0) ? r.x0 : r.x1;
            const int yMin  = r.y0 + 2;
            const int yMax  = r.y1 - 2;
            if (yMin > yMax) return;
            int doorY = (r.y0 + r.y1) / 2;
            doorY = std::max(yMin, std::min(yMax, doorY));

            set(doorX, doorY, TILE_DOOR, zone, 0, false);
            set(doorX, doorY-1, TILE_GLASS, zone);
            set(doorX, doorY+1, TILE_GLASS, zone);
        }
    };

    struct SegmentSpec
    {
        uint8_t zone = Z_NONE;
        uint8_t wall = TILE_METAL;
        bool big = false;     // one big room per side
        int baseLen = 64;     // scaled to fit map height
        int roomH = 28;       // only used for grid segments
    };

    // Decorative helpers ------------------------------------------------------

    void addTheaterScreens(MapWriter& m, const Rect& room, bool backIsLeftWall, uint8_t wallType)
    {
        // Mark a vertical band on the back wall as a "screen" using meta=1.
        const int x = backIsLeftWall ? room.x0 : room.x1;
        const int yMin = room.y0 + 4;
        const int yMax = room.y1 - 4;
        if (yMax <= yMin) return;

        const int mid = (yMin + yMax) / 2;
        const int half = std::min(10, (yMax - yMin) / 2);
        for (int y = mid - half; y <= mid + half; ++y)
            m.set(x, y, wallType, Z_THEATER, 1u, false);
    }

    void decorateBrigCells(MapWriter& m, const Rect& brigRoom, bool leftSide)
    {
        // Simple cell block strip near the outer wall. Cell doors are normal doors
        // but the shader will render them as barred when zone==Z_BRIG.
        const int cellDepth = 10;
        const int cellH = 12;
        const int inset = 2;

        const int iy0 = brigRoom.y0 + inset;
        const int iy1 = brigRoom.y1 - inset;

        if (iy1 - iy0 < cellH*2) return;

        int cx0, cx1, doorX, frontSide;
        if (leftSide)
        {
            cx0 = brigRoom.x0 + inset;
            cx1 = cx0 + cellDepth - 1;
            doorX = cx1;
            frontSide = 1; // right
        }
        else
        {
            cx1 = brigRoom.x1 - inset;
            cx0 = cx1 - cellDepth + 1;
            doorX = cx0;
            frontSide = 0; // left
        }

        int y = iy0;
        while (y + cellH - 1 <= iy1)
        {
            Rect cell{cx0, y, cx1, y + cellH - 1};
            m.carveRoom(cell, TILE_METAL, Z_BRIG);

            // One barred door per cell (no windows; bars handle the look).
            const int yMin = cell.y0 + 2;
            const int yMax = cell.y1 - 2;
            int doorY = (cell.y0 + cell.y1) / 2;
            doorY = std::max(yMin, std::min(yMax, doorY));
            m.set(doorX, doorY, TILE_DOOR, Z_BRIG, 0u, false);

            // Next cell shares a wall.
            y = cell.y1;
        }
    }

    void decorateStorageRacks(MapWriter& m, const Rect& storageRoom)
    {
        // Warehouse-style racks: long metal blocks with aisles.
        const int ix0 = storageRoom.x0 + 2;
        const int ix1 = storageRoom.x1 - 2;
        const int iy0 = storageRoom.y0 + 2;
        const int iy1 = storageRoom.y1 - 2;

        if (ix1 - ix0 < 20 || iy1 - iy0 < 20) return;

        const int rackW = 2;
        const int aisleW = 4;
        const int step = rackW + aisleW;

        // Start a little in so the entrance isn't immediately blocked.
        for (int x = ix0 + 6; x + rackW - 1 <= ix1 - 6; x += step)
        {
            // Leave a cross-aisle every so often.
            for (int y = iy0; y <= iy1; ++y)
            {
                if (((y - iy0) % 32) < 5) continue; // cross aisle slice
                for (int k = 0; k < rackW; ++k)
                    m.set(x + k, y, TILE_METAL, Z_STORAGE);
            }
        }
    }

    // Layout helpers ----------------------------------------------------------

    void carveHullAndMargin(MapWriter& m, int margin)
    {
        const int W = m.W, H = m.H;

        // Hull: full window border.
        for (int x=0; x<W; ++x)
        {
            m.set(x, 0,   TILE_GLASS, Z_CORRIDOR);
            m.set(x, H-1, TILE_GLASS, Z_CORRIDOR);
        }
        for (int y=0; y<H; ++y)
        {
            m.set(0,   y, TILE_GLASS, Z_CORRIDOR);
            m.set(W-1, y, TILE_GLASS, Z_CORRIDOR);
        }

        // Margin corridors (inside the hull): a 4-tile walkway band.
        const int xL0 = 1;
        const int xL1 = margin;
        const int xR0 = W-1-margin;
        const int xR1 = W-2;
        const int yT0 = 1;
        const int yT1 = margin;
        const int yB0 = H-1-margin;
        const int yB1 = H-2;

        // Vertical bands.
        m.fillRect(xL0, 1, xL1, H-2, TILE_EMPTY, Z_CORRIDOR);
        m.fillRect(xR0, 1, xR1, H-2, TILE_EMPTY, Z_CORRIDOR);

        // Horizontal bands.
        m.fillRect(1, yT0, W-2, yT1, TILE_EMPTY, Z_CORRIDOR);
        m.fillRect(1, yB0, W-2, yB1, TILE_EMPTY, Z_CORRIDOR);
    }

    void carveCrossHallway(MapWriter& m, int y0, int y1)
    {
        m.fillRect(1, y0, m.W-2, y1, TILE_EMPTY, Z_CORRIDOR);
    }

    void carveCenterCorridor(MapWriter& m, int x0, int x1)
    {
        m.fillRect(x0, 1, x1, m.H-2, TILE_EMPTY, Z_CORRIDOR);
    }

    void carveBridge(MapWriter& m, int bridgeDepth)
    {
        // Open, full-width top region.
        m.fillRect(1, 1, m.W-2, bridgeDepth, TILE_EMPTY, Z_BRIDGE);
    }

    void carveBigRoomPerSide(MapWriter& m,
                             int segY0, int segY1,
                             int cx0, int cx1,
                             int margin,
                             uint8_t zone,
                             uint8_t wallType,
                             bool addFrontDoor,
                             bool isTheater)
    {
        const int W = m.W;
        const Rect left  { margin+1, segY0, cx0-1, segY1 };
        const Rect right { cx1+1, segY0, W-margin-2, segY1 };

        m.carveRoom(left,  wallType, zone);
        m.carveRoom(right, wallType, zone);

        // Front faces the center corridor.
        if (addFrontDoor)
        {
            m.addFrontDoorAndWindows(left,  1, zone); // right wall
            m.addFrontDoorAndWindows(right, 0, zone); // left wall
        }

        if (isTheater)
        {
            // Screens on the back walls (opposite the corridor-facing door).
            addTheaterScreens(m, left,  true,  wallType);
            addTheaterScreens(m, right, false, wallType);
        }
    }

    void carveGridRooms(MapWriter& m,
                        int segY0, int segY1,
                        int cx0, int cx1,
                        int margin,
                        uint8_t zone,
                        uint8_t wallType,
                        int roomH)
    {
        const int W = m.W;
        const int xL0 = margin+1;
        const int xL1 = cx0-1;
        const int xR0 = cx1+1;
        const int xR1 = W-margin-2;

        const int spanL = xL1 - xL0 + 1;
        const int colWL = (spanL + 1) / 2;
        const Rect leftOuterBase { xL0, 0, xL0 + colWL - 1, 0 };
        const Rect leftInnerBase { leftOuterBase.x1, 0, xL1, 0 };

        const int spanR = xR1 - xR0 + 1;
        const int colWR = (spanR + 1) / 2;
        const Rect rightInnerBase { xR0, 0, xR0 + colWR - 1, 0 };
        const Rect rightOuterBase { rightInnerBase.x1, 0, xR1, 0 };

        int y = segY0;
        while (y + roomH - 1 <= segY1)
        {
            const int y0 = y;
            const int y1 = y + roomH - 1;

            Rect LOuter{ leftOuterBase.x0, y0, leftOuterBase.x1, y1 };
            Rect LInner{ leftInnerBase.x0, y0, leftInnerBase.x1, y1 };
            Rect RInner{ rightInnerBase.x0, y0, rightInnerBase.x1, y1 };
            Rect ROuter{ rightOuterBase.x0, y0, rightOuterBase.x1, y1 };

            m.carveRoom(LOuter, wallType, zone);
            m.carveRoom(LInner, wallType, zone);
            m.carveRoom(RInner, wallType, zone);
            m.carveRoom(ROuter, wallType, zone);

            // Doors: each room faces a hallway.
            // Left side: inner faces center corridor (right wall), outer faces margin corridor (left wall).
            m.addFrontDoorAndWindows(LInner, 1, zone);
            m.addFrontDoorAndWindows(LOuter, 0, zone);
            // Right side: inner faces center corridor (left wall), outer faces margin corridor (right wall).
            m.addFrontDoorAndWindows(RInner, 0, zone);
            m.addFrontDoorAndWindows(ROuter, 1, zone);

            // Next room row shares a wall.
            y = y1;
        }

        // Any leftover space becomes corridor so it doesn't trap anything.
        if (y <= segY1)
            carveCrossHallway(m, y, segY1);
    }

} // namespace

Result generate_bsp_ship(const Params& p)
{
    Result out;
    out.width  = p.width;
    out.height = p.height;

    const int W = int(p.width);
    const int H = int(p.height);

    // A safe fallback if someone passes a tiny map.
    if (W < 64 || H < 128)
    {
        out.cells.assign(size_t(W) * size_t(H), packCell(TILE_EMPTY, 0, false, Z_CORRIDOR));
        out.spawnX = 2.5f;
        out.spawnY = float(H - 3) + 0.5f;
        return out;
    }

    // Start as a solid deck of metal; carve from there.
    out.cells.assign(size_t(W) * size_t(H), packCell(TILE_METAL, 0, false, Z_NONE));

    MapWriter m;
    m.W = W;
    m.H = H;
    m.cells = &out.cells;

    const int margin = 4;
    const int crossT = 3;
    const int bridgeDepth = std::min(30, H - 2 - margin - 8);

    const int corrW = 7; // odd
    const int cx0 = (W / 2) - (corrW / 2);
    const int cx1 = cx0 + corrW - 1;

    // Hard limits for where "rooms" may exist (leave bottom margin untouched).
    const int endY = H - margin - 2;

    carveHullAndMargin(m, margin);
    carveCenterCorridor(m, cx0, cx1);
    carveBridge(m, bridgeDepth);

    // Between the bridge and the first segment, put a cross-hallway.
    int y = bridgeDepth + 1;
    carveCrossHallway(m, y, y + crossT - 1);
    y += crossT;

    // Segment plan (north -> south). These base lengths are scaled to fit the current map height.
    std::vector<SegmentSpec> segs = {
        // zone, wall, big, baseLen, roomH
        { Z_THEATER,  TILE_BRICK, true,  90, 0  },
        { Z_QUARTERS, TILE_METAL, false, 230, 28 },
        { Z_LABS,     TILE_METAL, false, 160, 32 },
        { Z_DINING,   TILE_METAL, false, 110, 28 },
        { Z_GARDENS,  TILE_METAL, true,  110, 0  },
        { Z_BRIG,     TILE_METAL, true,   90, 0  },
        { Z_STORAGE,  TILE_METAL, true,  177, 0  },
    };

    // Scale segment lengths to fit the available vertical space.
    const int available = std::max(0, endY - y + 1);
    const int needCross = crossT * int(segs.size() > 0 ? (segs.size() - 1) : 0);
    const int segSpace  = std::max(0, available - needCross);

    int baseSum = 0;
    for (auto& s : segs) baseSum += s.baseLen;
    const float scale = (baseSum > 0) ? (float(segSpace) / float(baseSum)) : 1.0f;

    int used = 0;
    for (size_t i=0; i<segs.size(); ++i)
    {
        if (i + 1 == segs.size())
        {
            segs[i].baseLen = std::max(24, segSpace - used);
        }
        else
        {
            int len = int(std::lround(float(segs[i].baseLen) * scale));
            len = std::max(24, len);
            segs[i].baseLen = len;
            used += len;
        }
    }

    // Carve segments.
    for (size_t i=0; i<segs.size(); ++i)
    {
        const SegmentSpec& s = segs[i];
        const int segY0 = y;
        const int segY1 = std::min(endY, segY0 + s.baseLen - 1);
        if (segY0 > endY) break;

        if (s.big)
        {
            const bool isTheater = (s.zone == Z_THEATER);
            carveBigRoomPerSide(m, segY0, segY1, cx0, cx1, margin, s.zone, s.wall, true, isTheater);

            // Zone-specific decoration.
            if (s.zone == Z_BRIG)
            {
                Rect left  { margin+1, segY0, cx0-1, segY1 };
                Rect right { cx1+1, segY0, W-margin-2, segY1 };
                decorateBrigCells(m, left,  true);
                decorateBrigCells(m, right, false);
            }
            else if (s.zone == Z_STORAGE)
            {
                Rect left  { margin+1, segY0, cx0-1, segY1 };
                Rect right { cx1+1, segY0, W-margin-2, segY1 };
                decorateStorageRacks(m, left);
                decorateStorageRacks(m, right);
            }
        }
        else
        {
            carveGridRooms(m, segY0, segY1, cx0, cx1, margin, s.zone, s.wall, s.roomH);
        }

        y = segY1 + 1;
        if (i + 1 < segs.size() && y + crossT - 1 <= endY)
        {
            carveCrossHallway(m, y, y + crossT - 1);
            y += crossT;
        }
    }

    // Any remaining space down to endY becomes corridor.
    if (y <= endY)
        carveCrossHallway(m, y, endY);

    // Suggested spawn: bottom of the deck on the center corridor.
    const int spawnCellY = std::max(1, H - 3);
    const int spawnCellX = (cx0 + cx1) / 2;
    out.spawnX = float(spawnCellX) + 0.5f;
    out.spawnY = float(spawnCellY) + 0.5f;

    // De-dup door indices (overlapping room edges can cause duplicates).
    std::sort(m.doorCells.begin(), m.doorCells.end());
    m.doorCells.erase(std::unique(m.doorCells.begin(), m.doorCells.end()), m.doorCells.end());

    out.doorCells = std::move(m.doorCells);
    return out;
}

} // namespace Starship_Raycaster::shipgen
