/*
    Starship Raycaster - A GPU-accelerated raycasting demo built with SDL3 and Vulkan.
    Copyright (C) 2026 Walter W. Whitman aka The Joyful Programmer (tm)
    Copyright (C) 2026 AstroCosmic Systems (tm)
    Copyright (C) 2026 Mini Yorkies Software (tm)

    This software is provided 'as-is', without any express or implied
    warranty.  In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.

    2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.

    3. This notice may not be removed or altered from any source distribution.

    This project is my attempt to build a modern GPU-accelerated raycasting demo
    in the spirit of classic 90s "2.5D" shooters, with a single-deck ship map as
    the main game overlay. It's also a personal sandbox for learning Vulkan and
    SDL3, and a testbed for various palette-building and quantization techniques.

    The code is organized into a few main components:
    - main.cpp: SDL3 app entrypoint and event loop, forwarding to App.
    - starship_raycaster.hpp/cpp: The main application class, Vulkan setup,
        rendering loop, and game overlay logic.
    - star_shipgen.hpp/cpp: A BSP-based procedural ship map generator, producing
        a grid of "tiles" that the raycaster renders.
    - star_palette.hpp/cpp: CPU palette-building utilities, including a perceptual
        palette builder based on a GPU-accelerated histogram.

    The project is built with C++26, and uses the Vulkan graphics API for rendering
    and SDL3 for windowing and input. It should compile and run on Windows, Linux,
    and macOS (with Vulkan support).

    The code is licensed under the zlib License (see above), which allows for free
    use and modification with minimal restrictions. Attribution is appreciated but
    not required.

    The testbed of palette-building techniques is a key part of the project, and includes:
    - A GPU-accelerated histogram builder that computes a 33^3 color histogram of
      the rendered image.
    - A CPU palette builder that takes the histogram and produces a 256-color palette
      using a weighted median-cut algorithm.
    - Support for preset palettes (e.g. EGA/VGA) and various dithering algorithms
      (Floyd-Steinberg, Bayer matrix, etc.).
    - A final display pass that looks up palette indices to show the quantized image.
    
    The game overlay is a simple GPU raycaster that renders a 2D grid-based map of "tiles"
    into a 3D view. The map is generated by a BSP-based algorithm that creates rooms,
    corridors, and zones with different themes. The raycaster supports walls, doors,
    stairs, and sprites (for NPCs or decorations). The player can move around the map and
    interact with doors.
    
    The project is a work in progress and may contain rough edges or incomplete features.
    
    Enjoy exploring the code and the demo!
*/
#pragma once
#include <array>
#include <cstdint>
#include <vector>

namespace star::pal
{
    struct RGB8 { uint8_t r=0, g=0, b=0; };

    enum class PalettePreset : uint32_t
    {
        Grayscale  = 0,           // key '0'
        Perceptual = 1,            // key '1'
        Green33   = 2,             // #000000 -> #33FF33
        Green66   = 3,             // #000000 -> #66FF66
        GoldCC    = 4,             // #000000 -> #FFCC00
        GoldB0    = 5,             // #000000 -> #FFB000
        VGA256    = 6,             // VGA-ish 256 default
        ColorTheory = 7,           // interactive hue/luma scheme
        MutedTeal = 8,            // #000000 -> #2F7875
        Vermilion = 9,            // #000000 -> #C04D3E
    };

    enum class ColorTheoryScheme : uint32_t
    {
        Monochromatic = 0,
        SplitComplementary,
        Triadic,
        Analogous,
        Diad,
        Square,
        Tetradic,
        Count
    };

    // Dithering modes used by the quantize compute shader.
    enum class DitherMode : uint32_t
    {
        None = 0,
        FloydSteinberg = 1,
        Atkinson = 2,
        OrderedBayer = 3,
        JarvisJudiceNinke = 4,
        Stucki = 5,
        Riemersma = 6,
        BlueNoise = 7,
        // Variants for testing/benchmarking:
        FloydSteinbergLumaOnly = 8,
        FloydSteinbergBlock = 9,
    };

    // Build a 256-color palette from an RGBA8 buffer (row-major).
    // Ported from The Joyful Programmer's QB64 demo: "BuildPerceptualPalette".
    std::array<RGB8, 256> buildPerceptualPalette(const uint8_t* rgba, int w, int h);

    // Build a perceptual palette from a 33^3 histogram (u32 counts).
    // Intended to be fed by the GPU histogram compute shader.
    // Only the first colorsToUse entries are meaningful; the rest are filled safely.
    std::array<RGB8, 256> buildPerceptualPaletteFromHistogram33(const uint32_t* histogram33, uint32_t colorsToUse);

    std::array<RGB8, 256> buildGradient(RGB8 a, RGB8 b);

    // Build a gradient where the endpoint lands at (colorsToUse-1) instead of index 255.
    // The remaining entries are filled with the last valid color.
    std::array<RGB8, 256> buildGradientN(RGB8 a, RGB8 b, uint32_t colorsToUse);
    std::array<RGB8, 256> buildVga256();

    // Interactive "color theory" palette (256 colors).
    // - hue: 0..255 (wraps)
    // - luminance: 0..255 (0 black, 255 white)
    std::array<RGB8, 256> buildColorTheory(uint8_t hue, uint8_t luminance, ColorTheoryScheme scheme);

    // Color-theory palette scaled to the active number of index colors.
    // We build the full 256-color grid then downsample so indices 0..colorsToUse-1 span the gamut.
    std::array<RGB8, 256> buildColorTheoryN(uint8_t hue, uint8_t luminance, ColorTheoryScheme scheme, uint32_t colorsToUse);

    // Build a compact 33^3 3D LUT that maps a quantized RGB (0..255) to a palette index [0..colorsToUse-1].
    // Distance is the same weighted RGB distance used in the BASIC demo: 30*dr^2 + 59*dg^2 + 11*db^2.
    std::vector<uint32_t> buildLut33(const std::array<RGB8,256>& pal, uint32_t colorsToUse);

    // Helpers: pack/unpack
    inline uint32_t packRGB(RGB8 c) { return (uint32_t(c.r) << 16) | (uint32_t(c.g) << 8) | uint32_t(c.b); }
}
