/*
    Starship Raycaster - A GPU-accelerated raycasting demo built with SDL3 and Vulkan.
    Copyright (C) 2026 Walter W. Whitman aka The Joyful Programmer (tm)
    Copyright (C) 2026 AstroCosmic Systems (tm)
    Copyright (C) 2026 Mini Yorkies Software (tm)

    This software is provided 'as-is', without any express or implied
    warranty.  In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.

    2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.

    3. This notice may not be removed or altered from any source distribution.

    This project is my attempt to build a modern GPU-accelerated raycasting demo
    in the spirit of classic 90s "2.5D" shooters, with a single-deck ship map as
    the main game overlay. It's also a personal sandbox for learning Vulkan and
    SDL3, and a testbed for various palette-building and quantization techniques.

    The code is organized into a few main components:
    - main.cpp: SDL3 app entrypoint and event loop, forwarding to App.
    - starship_raycaster.hpp/cpp: The main application class, Vulkan setup,
        rendering loop, and game overlay logic.
    - star_shipgen.hpp/cpp: A BSP-based procedural ship map generator, producing
        a grid of "tiles" that the raycaster renders.
    - star_palette.hpp/cpp: CPU palette-building utilities, including a perceptual
        palette builder based on a GPU-accelerated histogram.

    The project is built with C++26, and uses the Vulkan graphics API for rendering
    and SDL3 for windowing and input. It should compile and run on Windows, Linux,
    and macOS (with Vulkan support).

    The code is licensed under the zlib License (see above), which allows for free
    use and modification with minimal restrictions. Attribution is appreciated but
    not required.

    The testbed of palette-building techniques is a key part of the project, and includes:
    - A GPU-accelerated histogram builder that computes a 33^3 color histogram of
      the rendered image.
    - A CPU palette builder that takes the histogram and produces a 256-color palette
      using a weighted median-cut algorithm.
    - Support for preset palettes (e.g. EGA/VGA) and various dithering algorithms
      (Floyd-Steinberg, Bayer matrix, etc.).
    - A final display pass that looks up palette indices to show the quantized image.
    
    The game overlay is a simple GPU raycaster that renders a 2D grid-based map of "tiles"
    into a 3D view. The map is generated by a BSP-based algorithm that creates rooms,
    corridors, and zones with different themes. The raycaster supports walls, doors,
    stairs, and sprites (for NPCs or decorations). The player can move around the map and
    interact with doors.
    
    The project is a work in progress and may contain rough edges or incomplete features.
    
    Enjoy exploring the code and the demo!
*/
#pragma once

#include <SDL3/SDL.h>
#include <vulkan/vulkan.h>

#include <array>
#include <cstdint>
#include <string>
#include <vector>

#include "star_palette.hpp"

namespace Starship_Raycaster
{
    // Simple Vulkan + SDL3 demo scaffold (Rung 2):
    // - Render an effect shader to an offscreen RGBA image.
    // - Build a 256-color palette (perceptual or preset) on the CPU.
    // - Build a 33^3 LUT for fast nearest-color lookup.
    // - Quantize the offscreen image into an R8_UINT index image on the GPU (compute shader),
    //   with selectable dithering methods.
    // - Display the indexed image by looking up the palette in a final fullscreen pass.

    struct Frame
    {
        VkCommandBuffer commandBuffer = VK_NULL_HANDLE;
        VkSemaphore imageAvailableSemaphore = VK_NULL_HANDLE;
        VkSemaphore renderFinishedSemaphore = VK_NULL_HANDLE;
        VkFence inFlightFence = VK_NULL_HANDLE;

        // Per-frame readback buffer for palette construction (small downsampled image).
        VkBuffer readbackBuffer = VK_NULL_HANDLE;
        VkDeviceMemory readbackMemory = VK_NULL_HANDLE;
        void* readbackMapped = nullptr;
        uint32_t readbackW = 0;
        uint32_t readbackH = 0;
        bool readbackValid = false;
    };

    struct Effect
    {
        std::string name;
        std::string fragSpvPath;   // runtime path under build/shaders/...
        VkShaderModule fragModule = VK_NULL_HANDLE;
        VkPipeline pipeline = VK_NULL_HANDLE;
    };

    struct ImageRes
    {
        VkImage image = VK_NULL_HANDLE;
        VkDeviceMemory memory = VK_NULL_HANDLE;
        VkImageView view = VK_NULL_HANDLE;
        VkFormat format = VK_FORMAT_UNDEFINED;
        VkExtent2D extent{};
    };

    struct BufferRes
    {
        VkBuffer buffer = VK_NULL_HANDLE;
        VkDeviceMemory memory = VK_NULL_HANDLE;
        VkDeviceSize size = 0;
        void* mapped = nullptr;
    };


    static constexpr uint32_t MAX_SPRITES = 10000000; //48;

    // GPU sprite record (std430): 32 bytes.
    // posSize = (x, y, z, size)
    // meta.x  = atlas tile index (uint)
    // meta.y  = flags (unused for now)
    struct alignas(16) SpriteGPU
    {
        float x = 0.0f;
        float y = 0.0f;
        float z = 0.0f;
        float size = 1.0f;
        uint32_t tile = 0u;
        uint32_t flags = 0u;
        uint32_t pad0 = 0u;
        uint32_t pad1 = 0u;
    };

    struct SpriteCPU
    {
        float x = 0.0f;
        float y = 0.0f;
        float z = 0.0f;
        float size = 1.0f;
        uint32_t tile = 0u;
        uint32_t flags = 0u;
        float vx = 0.0f;
        float vy = 0.0f;
    };

    class App
    {
    public:
        explicit App(SDL_Window* window);
        ~App();

        App(const App&) = delete;
        App& operator=(const App&) = delete;

        void drawFrame();
        void onFramebufferResize(uint32_t w, uint32_t h);

        void onKeyDown(SDL_Keycode key, SDL_Keymod mod);

        // Mouse capture / focus helpers (SDL3 events forwarded from main.cpp)
        void onMouseButtonDown(uint8_t button);
        void onWindowFocusLost();

        // Relative mouse motion (xrel/yrel). Used for mouselook.
        void onMouseMotion(float x, float y, float dxRel, float dyRel);
        void onMouseWheel(float wheelY, SDL_Keymod mod, float mouseX, float mouseY);

    private:
        // --------- init / teardown ----------
        void initVulkan();
        void cleanup();

        void createInstance();
        void createSurface();
        void pickPhysicalDevice();
        void createLogicalDevice();
        void createCommandPool();
        void createSwapchain();
        void createSwapchainImageViews();
        void createCommandBuffers();
        void createSyncObjects();

        void createOffscreenResources();
        void createQuantizationResources();
        void createBlueNoiseResources();
        void createDescriptors();
        void createPipelines();

        // Final composite + CRT present pass (affects all layers).
        void createCompositeResources();
        void createPresentDescriptors();
        void loadEffectsFromDisk();

        void createReadbackResources(); // small image + per-frame staging buffers

        void cleanupSwapchain();
        void recreateSwapchain();

        // Pixel size changes only require rebuilding offscreen/index targets + descriptor sets.
        VkExtent2D computeRenderExtent() const;
        void recreatePostProcessTargets();


    public:
        // --------- game overlay (GPU raycaster) ----------
        // These are public so helper utilities in Starship_Raycaster.cpp can reference them.
        // Single-deck "ship level" map. Height is North/South; width is West/East.
        // The generator supports rectangular grids; defaults to 512x1024 (tall ship deck).
        static constexpr uint32_t DEFAULT_MAP_W = 512;
        static constexpr uint32_t DEFAULT_MAP_H = 1024;

        enum class TileType : uint32_t
        {
            Empty      = 0,
            Brick      = 1,
            Metal      = 2,
            Glass      = 3,
            Door       = 4,
            StairsUp   = 5,
            StairsDown = 6,
        };

    private:

        void initGame();
        void regenerateGameMap(uint32_t seed);
        void updateGame(double dtSeconds);
        void uploadGameMap(uint32_t frameSlot);
        void spawnSprites(uint32_t seed);
        void updateSprites(double dtSeconds);
        void uploadSprites(uint32_t frameSlot);
        void doorActionInFront(bool toggleLock);

        void createGameResources();
        void createGameDescriptors();
        void destroyGameResources();
        void destroyGameDescriptors();


        // --------- GUI / HUD overlay resources ----------
        void createGuiResources();
        void createGuiDescriptors();
        void destroyGuiResources();
        void destroyGuiDescriptors();


        // --------- utilities ----------
        VkShaderModule createShaderModuleFromFile(const std::string& filePath);
        std::vector<char> readFile(const std::string& filename);

        uint32_t findMemoryType(uint32_t typeFilter, VkMemoryPropertyFlags properties);
        void createBuffer(VkDeviceSize size, VkBufferUsageFlags usage, VkMemoryPropertyFlags properties,
                          VkBuffer& buffer, VkDeviceMemory& memory, void** mapped = nullptr);
        void destroyBuffer(VkBuffer& buffer, VkDeviceMemory& memory, void** mapped = nullptr);

        void createImage(uint32_t w, uint32_t h, VkFormat format, VkImageTiling tiling,
                         VkImageUsageFlags usage, VkMemoryPropertyFlags properties,
                         VkImage& image, VkDeviceMemory& memory);
        VkImageView createImageView(VkImage image, VkFormat format, VkImageAspectFlags aspectFlags);

        void transitionImageLayout(VkCommandBuffer cmd, VkImage image,
                                   VkImageLayout oldLayout, VkImageLayout newLayout,
                                   VkPipelineStageFlags2 srcStage, VkAccessFlags2 srcAccess,
                                   VkPipelineStageFlags2 dstStage, VkAccessFlags2 dstAccess,
                                   VkImageAspectFlags aspect = VK_IMAGE_ASPECT_COLOR_BIT);

        // --------- input (event + polling hybrid) ----------
        void handleKeyDown(SDL_Keycode key, SDL_Keymod mod);
        void pollKeyboard(bool allowEdges);

        void setMouseCaptured(bool captured);

        // Health/vignette coupling: vignette size <-> HUD health value.
        void syncHealthFromVignette();

        // Map SSBO resizing (when map dimensions change at runtime).
        void ensureGameMapSsboSized();

        // --------- palette system ----------
        void updatePaletteIfNeeded(uint32_t frameIndex); // writes into dynamic palette + LUT buffers
        void buildPerceptualPaletteFromReadback(const Frame& frame); // updates cpuPalette_

        void rebuildLut(); // cpuLut_ from cpuPalette_ + colorsToUse_
        void writeGpuPalette(uint32_t frameIndex);
        void writeGpuLut(uint32_t frameIndex);

        std::string currentStatusLine() const;

        // --------- state ----------
        SDL_Window* window_ = nullptr;
        VkInstance instance_ = VK_NULL_HANDLE;
        VkSurfaceKHR surface_ = VK_NULL_HANDLE;

        VkPhysicalDevice physicalDevice_ = VK_NULL_HANDLE;
        VkDevice device_ = VK_NULL_HANDLE;
        VkQueue graphicsQueue_ = VK_NULL_HANDLE;
        VkQueue presentQueue_ = VK_NULL_HANDLE;

        uint32_t graphicsQueueFamily_ = 0;
        uint32_t presentQueueFamily_ = 0;

        VkSwapchainKHR swapchain_ = VK_NULL_HANDLE;
        VkFormat swapchainFormat_ = VK_FORMAT_UNDEFINED;
        VkExtent2D swapchainExtent_{};

        std::vector<VkImage> swapchainImages_;
        std::vector<VkImageView> swapchainImageViews_;

        // Full-resolution composite target (display + GUI), sampled by the CRT present pass.
        std::vector<ImageRes> composite_;
        std::vector<VkImageLayout> compositeLayout_;

        VkCommandPool commandPool_ = VK_NULL_HANDLE;

        static constexpr int MAX_FRAMES_IN_FLIGHT = 2;
        std::array<Frame, MAX_FRAMES_IN_FLIGHT> frames_{};
        uint32_t currentFrame_ = 0;
        uint64_t frameCounter_ = 0;

        std::vector<VkFence> imagesInFlight_;

        bool framebufferDirty_ = false;

        // --------- offscreen + index resources (per swapchain image) ----------
        std::vector<ImageRes> offscreen_;
        std::vector<ImageRes> indexImage_;     // R8_UINT sampled + storage
        std::vector<BufferRes> errBuffers_;    // 3*width vec4 error diffusion buffer per swapchain image
        std::vector<BufferRes> histBuffers_;   // 33^3 histogram bins (u32) per swapchain image
        std::vector<uint8_t> histEverSubmitted_; // per swapchain image

        std::vector<VkImageLayout> offscreenLayout_;
        std::vector<VkImageLayout> indexLayout_;

        VkSampler srcSampler_ = VK_NULL_HANDLE;
        VkSampler indexSampler_ = VK_NULL_HANDLE;
        VkSampler presentSampler_ = VK_NULL_HANDLE; // linear sampler for composite -> present


        // Blue-noise (tileable mask) used by dither mode BlueNoise
        ImageRes blueNoise_{};
        VkSampler blueNoiseSampler_ = VK_NULL_HANDLE;

        bool bnDriftEnabled_ = true;
        uint32_t bnDriftDiv_ = 16; // frameCounter / div -> 1 texel drift per div frames

        // Swapchain layout tracking (per swapchain image)
        std::vector<VkImageLayout> swapchainLayouts_;

        // Readback: small per-frame image for palette construction (avoids cross-frame hazards)
        std::array<ImageRes, MAX_FRAMES_IN_FLIGHT> readbackImages_{}; // RGBA8
        std::array<VkImageLayout, MAX_FRAMES_IN_FLIGHT> readbackLayouts_{}; // track per-frame layout
        // --------- palette + LUT GPU buffers (dynamic storage buffers) ----------
        BufferRes paletteDyn_;
        BufferRes lutDyn_;
        VkDeviceSize paletteStride_ = 0;
        VkDeviceSize lutStride_ = 0;

        // CPU copies
        std::array<star::pal::RGB8,256> cpuPalette_{};
        std::vector<uint32_t> cpuLut_; // 33^3

        // Perceptual palette cache (built from readback every frame when enabled)
        std::array<star::pal::RGB8,256> perceptualPalette_{};
        uint64_t perceptualGen_ = 0;
        uint64_t appliedPerceptualGen_ = 0;
        bool perceptualReady_ = false;

        // Palette generation counter. Increment whenever cpuPalette_ meaningfully changes.
        uint64_t paletteGen_ = 1;

        // Per-frame-slot LUT cache tags. LUT is built on GPU into lutDyn_ slice for currentFrame_.
        std::array<uint64_t, MAX_FRAMES_IN_FLIGHT> lutBuiltGen_{};
        std::array<uint32_t, MAX_FRAMES_IN_FLIGHT> lutBuiltColors_{};

        // Keyboard edge polling (used when the OS stops delivering key events during interactive resize).
        uint64_t keyEventSerial_ = 0;
        uint64_t keyEventSerialSeen_ = 0;
        // SDL3 renamed the scancode count constant; SDL_NUM_SCANCODES is an old-name trap macro.
        std::array<uint8_t, SDL_SCANCODE_COUNT> keyPrev_{};
        bool keyPrevInit_ = false;

        bool paletteDirty_ = true;
        bool lutDirty_ = true;

        // --------- descriptors ----------
        VkDescriptorSetLayout descSetLayout_ = VK_NULL_HANDLE;
        VkDescriptorPool descPool_ = VK_NULL_HANDLE;
        std::vector<VkDescriptorSet> descSets_; // per swapchain image

        // Present pass (CRT) descriptor set: composite image sampler, per swapchain image
        VkDescriptorSetLayout presentDescSetLayout_ = VK_NULL_HANDLE;
        VkDescriptorPool      presentDescPool_ = VK_NULL_HANDLE;
        std::vector<VkDescriptorSet> presentDescSets_;

        // --------- pipelines ----------
        VkShaderModule fullscreenVert_ = VK_NULL_HANDLE;

        std::vector<Effect> effects_;
        int activeEffect_ = 0;

        VkPipelineLayout effectPipelineLayout_ = VK_NULL_HANDLE;

        VkPipeline quantizePipeline_ = VK_NULL_HANDLE;
        VkPipelineLayout quantizePipelineLayout_ = VK_NULL_HANDLE;

        VkPipeline histogramPipeline_ = VK_NULL_HANDLE;
        VkPipelineLayout histogramPipelineLayout_ = VK_NULL_HANDLE;

        VkPipeline lutBuildPipeline_ = VK_NULL_HANDLE;
        VkPipelineLayout lutBuildPipelineLayout_ = VK_NULL_HANDLE;

        VkPipeline displayPipeline_ = VK_NULL_HANDLE;
        VkPipelineLayout displayPipelineLayout_ = VK_NULL_HANDLE;

        // Full-color display pipeline (bypasses palette/indexing)
        VkPipeline fullcolorPipeline_ = VK_NULL_HANDLE;

        // Final CRT post-process pipeline (composite -> swapchain).
        VkPipelineLayout presentPipelineLayout_ = VK_NULL_HANDLE;
        VkPipeline       presentPipeline_ = VK_NULL_HANDLE;


        // --------- interactive settings ----------
        star::pal::PalettePreset palettePreset_ = star::pal::PalettePreset::Perceptual;

        uint32_t colorsToUse_ = 256;

        // Default: dithering OFF, but default algorithm is Floyd-Steinberg when enabled.
        bool ditheringEnabled_ = false;
        star::pal::DitherMode ditherMode_ = star::pal::DitherMode::FloydSteinberg;
        float ditherStrength_ = 1.0f;

        // Pixelation: render to a smaller backbuffer and scale up.
        // 1 = native resolution (offscreen matches window), 60 = very chunky (offscreen ~1/60th).
        // Default to native resolution (1). If you want more "CRT chunk", hit ' +' to increase pixel size at runtime.
        uint32_t pixelSize_ = 1; // (+/-) range [1..60] (default 1 = native)

        // Palette-index mode toggle (F):
        // - ON  : run GPU quantizer, display palette-indexed image
        // - OFF : bypass quantizer and display full-color offscreen image
        bool paletteIndexMode_ = true;


        // Always keep a fresh perceptual palette around (small 320x180 readback)
        bool alwaysBuildPerceptual_ = true;

        // Color-theory palette controls (preset 7)
        uint8_t ctHue_ = 0;          // 0..255
        uint8_t ctLuma_ = 128;       // 0..255
        star::pal::ColorTheoryScheme ctScheme_ = star::pal::ColorTheoryScheme::Monochromatic;

        // --------- time ----------
        double timeSeconds_ = 0.0;

        // --------- game overlay state ----------
        bool gameEnabled_ = true;
        float gameAlpha_ = 1.0f; // (,/.) in [0..1]
        uint32_t gameSeed_ = 1;        // Packed cell format:
        //  bits 0..7   = TileType
        //  bits 8..15  = door open fraction (0..255)
        //  bit  16     = locked
        //  bits 17..24 = zone id (0..255)
        uint32_t mapW_ = DEFAULT_MAP_W;
        uint32_t mapH_ = DEFAULT_MAP_H;

        std::vector<uint32_t> gameMapCpu_{};
        std::vector<float>    doorVel_{};   // -1..+1 anim velocity per cell
        std::vector<uint32_t> doorCells_{}; // indices of door cells (for fast iteration)


        std::array<BufferRes, MAX_FRAMES_IN_FLIGHT> gameMapBuf_{}; // SSBO per frame slot

        // Sprite list SSBO (for billboard NPCs, etc.)
        std::vector<SpriteCPU> sprites_{};
        uint32_t spriteCount_ = 0;
        std::array<BufferRes, MAX_FRAMES_IN_FLIGHT> spriteBuf_{};

        // Procedural world texture atlas for the raycaster (placeholder until KTX2).
        ImageRes  worldAtlas_{};
        VkSampler worldAtlasSampler_ = VK_NULL_HANDLE;

        VkDescriptorSetLayout gameDescSetLayout_ = VK_NULL_HANDLE;
        VkDescriptorPool      gameDescPool_ = VK_NULL_HANDLE;
        std::array<VkDescriptorSet, MAX_FRAMES_IN_FLIGHT> gameDescSets_{};

        VkShaderModule   gameFrag_ = VK_NULL_HANDLE;
        VkPipelineLayout gamePipelineLayout_ = VK_NULL_HANDLE;
        VkPipeline       gamePipeline_ = VK_NULL_HANDLE;

        // --------- health vignette overlay (3rd layer) ----------
        bool healthVignetteEnabled_ = true;
        float healthVignetteSizePx_ = 0.0f; // (F1/F2) clamped to [0..min(w/2,h/2)] ; 0 => 100% health

        VkShaderModule   healthFrag_ = VK_NULL_HANDLE;
        VkPipelineLayout healthPipelineLayout_ = VK_NULL_HANDLE;
        VkPipeline       healthPipeline_ = VK_NULL_HANDLE;

        // --------- GUI overlay (4th layer) ----------
        bool guiEnabled_ = true;

        enum class MinimapPos : uint32_t { TL = 0, TR = 1, BL = 2, BR = 3 };
        MinimapPos minimapPos_ = MinimapPos::TR;
        float minimapSizePx_ = 180.0f;

        // Full-size tactical map overlay (toggled with M).
        bool  fullMapWanted_ = false;
        float fullMapAlpha_  = 0.0f;   // fade 0..1

        // Full-map view transform (Option B): pan in map-cell units and a zoom multiplier.
        // zoom=1.0 uses the shader's fit-to-screen base scale.
        float fullMapPanXCells_ = 0.0f;
        float fullMapPanYCells_ = 0.0f;
        float fullMapPanXTargetCells_ = 0.0f;
        float fullMapPanYTargetCells_ = 0.0f;
        float fullMapZoom_ = 1.0f;
        float fullMapZoomTarget_ = 1.0f;

        // CRT map modes (0 = normal, 1..3 = increasingly cursed).
        uint32_t mapCrtMode_ = 0;

        // Optional: apply CRT treatment to legend too.
        bool mapCrtAffectsLegend_ = false;

        // Mouse capture state (TAB toggles; click to recapture).
        bool  mouseCaptured_ = false;
        float mouseHintAlpha_ = 0.0f;  // fades in when mouse is released

        // Last known mouse position in framebuffer pixel coordinates (used for zoom-to-cursor on tactical map).
        float mouseAbsX_ = 0.0f;
        float mouseAbsY_ = 0.0f;

        int hudHealth_ = 100;
        int hudAmmo_   = 50;

        // Procedural HUD atlas (digits + simple icons).
        ImageRes  hudAtlas_{};
        VkSampler hudAtlasSampler_ = VK_NULL_HANDLE;

        // Legend atlas (rendered with FreeType in a bolder font weight).
        ImageRes  legendAtlas_{};
        VkSampler legendAtlasSampler_ = VK_NULL_HANDLE;

        VkDescriptorSetLayout guiDescSetLayout_ = VK_NULL_HANDLE;
        VkDescriptorPool      guiDescPool_ = VK_NULL_HANDLE;
        std::array<VkDescriptorSet, MAX_FRAMES_IN_FLIGHT> guiDescSets_{};

        VkShaderModule   guiFrag_ = VK_NULL_HANDLE;
        VkPipelineLayout guiPipelineLayout_ = VK_NULL_HANDLE;
        VkPipeline       guiPipeline_ = VK_NULL_HANDLE;

        // Player
        float playerX_ = 3.5f;
        float playerY_ = 3.5f;
        float playerAngle_ = 0.0f;          // radians
        float playerPitchAngle_ = 0.0f;     // radians (-pi/2..+pi/2)
        float playerFov_ = 1.1519173f;      // ~66 degrees
        float playerEyeZ_ = 0.5f;
        float playerEyeZTarget_ = 0.5f;

        // Mouse-look tuning.
        float mouseYawSens_   = 0.0025f;    // radians per pixel
        float mousePitchSens_ = 0.0022f;    // radians per pixel

        double lastTimeSeconds_ = 0.0;
    };
} // namespace Starship_Raycaster
