/*
    Starship Raycaster - A GPU-accelerated raycasting demo built with SDL3 and Vulkan.
    Copyright (C) 2026 Walter W. Whitman aka The Joyful Programmer (tm)
    Copyright (C) 2026 AstroCosmic Systems (tm)
    Copyright (C) 2026 Mini Yorkies Software (tm)

    This software is provided 'as-is', without any express or implied
    warranty.  In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.

    2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.

    3. This notice may not be removed or altered from any source distribution.

    This project is my attempt to build a modern GPU-accelerated raycasting demo
    in the spirit of classic 90s "2.5D" shooters, with a single-deck ship map as
    the main game overlay. It's also a personal sandbox for learning Vulkan and
    SDL3, and a testbed for various palette-building and quantization techniques.

    The code is organized into a few main components:
    - main.cpp: SDL3 app entrypoint and event loop, forwarding to App.
    - starship_raycaster.hpp/cpp: The main application class, Vulkan setup,
        rendering loop, and game overlay logic.
    - star_shipgen.hpp/cpp: A BSP-based procedural ship map generator, producing
        a grid of "tiles" that the raycaster renders.
    - star_palette.hpp/cpp: CPU palette-building utilities, including a perceptual
        palette builder based on a GPU-accelerated histogram.

    The project is built with C++26, and uses the Vulkan graphics API for rendering
    and SDL3 for windowing and input. It should compile and run on Windows, Linux,
    and macOS (with Vulkan support).

    The code is licensed under the zlib License (see above), which allows for free
    use and modification with minimal restrictions. Attribution is appreciated but
    not required.

    The testbed of palette-building techniques is a key part of the project, and includes:
    - A GPU-accelerated histogram builder that computes a 33^3 color histogram of
      the rendered image.
    - A CPU palette builder that takes the histogram and produces a 256-color palette
      using a weighted median-cut algorithm.
    - Support for preset palettes (e.g. EGA/VGA) and various dithering algorithms
      (Floyd-Steinberg, Bayer matrix, etc.).
    - A final display pass that looks up palette indices to show the quantized image.
    
    The game overlay is a simple GPU raycaster that renders a 2D grid-based map of "tiles"
    into a 3D view. The map is generated by a BSP-based algorithm that creates rooms,
    corridors, and zones with different themes. The raycaster supports walls, doors,
    stairs, and sprites (for NPCs or decorations). The player can move around the map and
    interact with doors.
    
    The project is a work in progress and may contain rough edges or incomplete features.
    
    Enjoy exploring the code and the demo!
*/
#version 450

// Full-screen triangle path uses no vertex buffers and therefore provides
// no varyings. Use gl_FragCoord for pixel coordinates.
layout(location = 0) out vec4 outColor;

layout(push_constant) uniform PC
{
    // a = (renderW, renderH, time, alpha)
    vec4 a;
    // b = (playerX, playerY, playerAngle, unused)
    vec4 b;
    // c = (eyeZ, spriteCount, maxHits, unused)
    vec4 c;
    // d = (mapW, mapH, reserved, reserved)
    uvec4 d;
} pc;

layout(set = 0, binding = 0, std430) readonly buffer MapBuf
{
    uint cells[];
} mapBuf;

struct SpriteGPU
{
    vec4 posSize;   // (x, y, z, size)
    uvec4 meta;     // (tileIndex, flags, pad, pad)
};

layout(set = 0, binding = 2, std430) readonly buffer SpriteBuf
{
    SpriteGPU sprites[];
} sprBuf;

layout(set = 0, binding = 1) uniform sampler2D worldAtlas;

// -----------------------------------------------------------------------------
// Atlas + map encoding
// -----------------------------------------------------------------------------

// IMPORTANT: These must match App::TileType in C++ (star_vulkan.hpp)
// Empty=0, Brick=1, Metal=2, Glass=3, Door=4, StairsUp=5, StairsDown=6
const uint TILE_EMPTY      = 0u;
const uint TILE_BRICK      = 1u;
const uint TILE_METAL      = 2u;
const uint TILE_GLASS      = 3u;
const uint TILE_DOOR       = 4u;
const uint TILE_STAIRS_UP  = 5u;
const uint TILE_STAIRS_DN  = 6u;

// Atlas tiles (GRID 8x8). Keep consistent with C++ procedural atlas in createGameResources().
uint atlasForWallBasic(uint t)
{
    if (t == TILE_BRICK) return 1u;
    if (t == TILE_METAL) return 2u;
    if (t == TILE_GLASS) return 3u;
    if (t == TILE_DOOR)  return 4u;
    return 1u;
}

// -----------------------------------------------------------------------------
// Map cell decode helpers
// -----------------------------------------------------------------------------
// GLSL requires functions to be declared before first use.
uint cellType(uint cell);
uint doorOpen8(uint cell);
bool cellLocked(uint cell);
uint cellZone(uint cell);

// Zone-aware wall atlas selection.
// Uses doorOpen8(cell) as a lightweight "variant" byte for non-door walls.
uint atlasForWallCell(uint cell)
{
    const uint t = cellType(cell);
    const uint z = cellZone(cell);
    const uint v = doorOpen8(cell);

    // Brig: barred/transparent cell doors.
    if (t == TILE_DOOR)
    {
        if (z == 3u) return 5u;
        return 4u;
    }

    // Theater: dark red walls + optional screen patch on the back wall.
    if (z == 7u)
    {
        if (v == 1u) return 8u; // screen
        return 7u;              // wall
    }

    // Labs: half-window wall look.
    if (z == 2u && (t == TILE_METAL || t == TILE_BRICK))
    {
        return 6u;
    }

    return atlasForWallBasic(t);
}

uint atlasForFloor(uint t)
{
    // C++ atlas: 16=floor
    // (parameter kept for future per-tile floor mapping)
    return 16u;
}

uint atlasForCeil(uint t)
{
    // C++ atlas: 17=ceiling
    // (parameter kept for future per-tile ceiling mapping)
    return 17u;
}

// Zone-themed floor/ceiling tiles.
// Zone IDs come from the generator and are packed in bits [17..24].
//  1: Quarters
//  2: Labs
//  3: Brig
//  4: Storage
//  5: Garden
//  6: Dining
//  7: Theater
//  8: Recreation
// 200: Main corridors/spine
uint atlasForFloorCell(uint cell)
{
    uint z = cellZone(cell);
    if (z == 1u) return 18u;
    if (z == 2u) return 19u;
    if (z == 3u) return 20u;
    if (z == 4u) return 21u;
    if (z == 5u) return 22u;
    if (z == 6u) return 23u;
    if (z == 7u) return 24u;
    if (z == 8u) return 25u;
    // corridors + default
    return 16u;
}

uint atlasForCeilCell(uint cell)
{
    uint z = cellZone(cell);
    if (z == 1u) return 26u;
    if (z == 2u) return 27u;
    if (z == 3u) return 28u;
    if (z == 4u) return 29u;
    if (z == 5u) return 30u;
    if (z == 6u) return 31u;
    if (z == 7u) return 33u;
    if (z == 8u) return 34u;
    return 17u;
}

const uint GRID = 8u;

vec4 sampleAtlas(uint tile, vec2 tuv)
{
    // Clamp to avoid sampling outside the tile.
    tuv = clamp(tuv, vec2(0.0), vec2(0.999999));
    uint tx = tile % GRID;
    uint ty = tile / GRID;
    vec2 base = vec2(float(tx), float(ty)) / float(GRID);
    vec2 uvAtlas = base + (tuv / float(GRID));
    return texture(worldAtlas, uvAtlas);
}

uvec2 mapSize() { return pc.d.xy; }

bool inBounds(ivec2 p)
{
    uvec2 ms = mapSize();
    return (p.x >= 0 && p.y >= 0 && p.x < int(ms.x) && p.y < int(ms.y));
}

uint idxOf(ivec2 p)
{
    return uint(p.y) * mapSize().x + uint(p.x);
}

uint cellAt(ivec2 p)
{
    if (!inBounds(p)) return 0u;
    return mapBuf.cells[idxOf(p)];
}

uint cellType(uint cell)       { return (cell & 0xFFu); }
uint doorOpen8(uint cell)      { return (cell >> 8) & 0xFFu; }
bool cellLocked(uint cell)     { return ((cell >> 16) & 1u) != 0u; }
uint cellZone(uint cell)       { return (cell >> 17) & 0xFFu; }

bool isOpenForDoorAxis(uint t)
{
    // Treat only true open tiles as open for orientation detection.
    return (t == TILE_EMPTY || t == TILE_STAIRS_UP || t == TILE_STAIRS_DN);
}

int doorAxisForCell(ivec2 p)
{
    // Returns 0 for normal X (door plane vertical), 1 for normal Y (door plane horizontal)
    bool oL = isOpenForDoorAxis(cellType(cellAt(p + ivec2(-1, 0))));
    bool oR = isOpenForDoorAxis(cellType(cellAt(p + ivec2(+1, 0))));
    bool oU = isOpenForDoorAxis(cellType(cellAt(p + ivec2(0, -1))));
    bool oD = isOpenForDoorAxis(cellType(cellAt(p + ivec2(0, +1))));

    if ((oL || oR) && !(oU || oD)) return 0;
    if ((oU || oD) && !(oL || oR)) return 1;
    // Tie-break: favor X
    return 0;
}

// -----------------------------------------------------------------------------
// Ray casting
// -----------------------------------------------------------------------------

struct Hit
{
    bool hit;
    bool exited;
    float dist;     // distance along ray from current ray origin
    int side;       // 0 => x-normal, 1 => y-normal
    uint type;      // map cell type
    uint tile;      // atlas tile index
    float slide;    // door slide amount (0..1) along tangent (for u-shift)
    bool locked;
};

Hit makeNoHit()
{
    Hit h;
    h.hit = false;
    h.exited = false;
    h.dist = 1e30;
    h.side = 0;
    h.type = TILE_EMPTY;
    h.tile = 0u;
    h.slide = 0.0;
    h.locked = false;
    return h;
}

Hit makeExit(float dist)
{
    Hit h = makeNoHit();
    h.exited = true;
    h.dist = dist;
    return h;
}

Hit makeHit(float dist, int side, uint type, uint tile, float slide, bool locked)
{
    Hit h;
    h.hit = true;
    h.exited = false;
    h.dist = dist;
    h.side = side;
    h.type = type;
    h.tile = tile;
    h.slide = slide;
    h.locked = locked;
    return h;
}

// DDA. Returns nearest wall/door surface. If allowExit is true and ray leaves the map,
// we return exited=true (so the caller can make the background transparent).
Hit traceRay(vec2 ro, vec2 rd, bool allowExit)
{
    ivec2 ms = ivec2(mapSize());

    ivec2 mp = ivec2(floor(ro));

    // Avoid division by zero.
    vec2 inv = vec2(
        (abs(rd.x) < 1e-8) ? 1e8 : 1.0 / rd.x,
        (abs(rd.y) < 1e-8) ? 1e8 : 1.0 / rd.y
    );
    vec2 delta = abs(inv);

    ivec2 step = ivec2((rd.x < 0.0) ? -1 : 1, (rd.y < 0.0) ? -1 : 1);

    vec2 sideDist;
    sideDist.x = (rd.x < 0.0) ? (ro.x - float(mp.x)) * delta.x : (float(mp.x) + 1.0 - ro.x) * delta.x;
    sideDist.y = (rd.y < 0.0) ? (ro.y - float(mp.y)) * delta.y : (float(mp.y) + 1.0 - ro.y) * delta.y;

    // Safety/perf: cap DDA steps based on map dimensions.
    // For a WxH grid, you will never need more than ~W+H steps to leave the map.
    // Keeping this lower prevents driver timeouts on huge maps.
    int maxSteps = int(mapSize().x + mapSize().y) + 8;
    maxSteps = clamp(maxSteps, 64, 1024);

    // Also cap view distance so pathological rays don't chew the GPU.
    const float MAX_VIEW_DIST = 256.0;

    for (int i = 0; i < maxSteps; ++i)
    {
        int side = (sideDist.x < sideDist.y) ? 0 : 1;
        if (side == 0) { sideDist.x += delta.x; mp.x += step.x; }
        else           { sideDist.y += delta.y; mp.y += step.y; }

        float tEnter = (side == 0) ? (sideDist.x - delta.x) : (sideDist.y - delta.y);
        float tExit  = min(sideDist.x, sideDist.y);

        if (tEnter > MAX_VIEW_DIST)
        {
            if (allowExit) return makeExit(tEnter);
            return makeNoHit();
        }

        if (!inBounds(mp))
        {
            if (allowExit) return makeExit(tEnter);
            // Treat outside as a solid wall (use METAL as the default).
            return makeHit(tEnter, side, TILE_METAL, atlasForWallBasic(TILE_METAL), 0.0, false);
        }

        uint cell = cellAt(mp);
        uint t = cellType(cell);
        bool locked = cellLocked(cell);

        if (t == TILE_EMPTY) continue;

        if (t != TILE_DOOR)
        {
            uint tile = atlasForWallCell(cell);
            return makeHit(tEnter, side, t, tile, 0.0, locked);
        }

        // Door slab geometry:
        // - full width/height of a tile
        // - depth = 1/4 tile, centered at 9/16 (between 4/8 and 5/8)
        // - slides along tangent axis (like Wolf3D / Rise of the Triad)
        float open01 = float(doorOpen8(cell)) / 255.0;
        open01 = clamp(open01, 0.0, 1.0);

        // Fully open -> skip quickly.
        if (open01 >= 0.999) continue;

        int axis = doorAxisForCell(mp);
        float depthCenter = 9.0 / 16.0;
        float halfDepth   = 1.0 / 8.0;   // 0.125 (depth 0.25)

        float rdn = (axis == 0) ? rd.x : rd.y;
        if (abs(rdn) < 1e-8) continue;

        float planeLocal = depthCenter - halfDepth * sign(rdn); // near face
        float planeWorld = (axis == 0) ? (float(mp.x) + planeLocal) : (float(mp.y) + planeLocal);
        float ron = (axis == 0) ? ro.x : ro.y;

        float tPlane = (planeWorld - ron) / rdn;
        if (tPlane <= tEnter || tPlane >= tExit) continue;

        vec2 hp = ro + rd * tPlane;

        // Sliding along tangent axis by open01: inside-cell portion exists only when tangLocal >= open01
        float tangLocal = (axis == 0) ? fract(hp.y) : fract(hp.x);
        if (tangLocal < open01) continue; // passed through the open gap

        // Door hit: side should match the door axis normal (0 => x-normal, 1 => y-normal)
        // Use zone-aware atlas selection so brig doors can render as barred doors.
        uint atlasTile = atlasForWallCell(cell);
        return makeHit(tPlane, axis, TILE_DOOR, atlasTile, open01, locked);
    }

    return makeNoHit();
}

vec4 shadeWallPixel(vec2 ro, vec2 rd, float py, float pitch, float eyeZ, Hit h)
{
    float w = pc.a.x;
    float H = pc.a.y;

    float dist = max(h.dist, 1e-4);
    float lineH = H / dist;

    // Slight eye height shift, no perspective correction beyond that.
    float centerY = (H * 0.5) + pitch;

    float wallStart = (-lineH * 0.5) + centerY;
    float wallEnd   = ( lineH * 0.5) + centerY;

    if (py < wallStart || py > wallEnd) return vec4(0.0, 0.0, 0.0, -1.0);

    vec2 hitPos = ro + rd * dist;

    // Horizontal texture coordinate.
    float u = (h.side == 0) ? hitPos.y : hitPos.x;

    // Sliding door shifts along tangent axis (u axis).
    if (h.type == TILE_DOOR)
        u -= h.slide;

    u = fract(u);

    // Keep winding consistent.
    if (h.side == 0 && rd.x > 0.0) u = 1.0 - u;
    if (h.side == 1 && rd.y < 0.0) u = 1.0 - u;

    float v = (py - wallStart) / max(lineH, 1e-6);

    vec4 tex = sampleAtlas(h.tile, vec2(u, v));

    // Side lighting only (no distance darkening).
    if (h.side == 1) tex.rgb *= 0.85;

    // Locked door hint: subtle red bar near the bottom.
    if (h.type == TILE_DOOR && h.locked)
    {
        if (v > 0.82 && v < 0.90)
            tex.rgb = mix(tex.rgb, vec3(0.85, 0.18, 0.12), 0.55);
    }

    return tex;
}

vec4 shadeFloorOrCeil(vec2 ro, vec2 rd, float py, float pitch, float eyeZ, float minDist)
{
    float H = pc.a.y;
    float p = (py - (H * 0.5) - pitch);

    // p>0 => floor, p<0 => ceiling
    float denom = (abs(p) < 1e-4) ? 1e-4 : p;

    float posZ = eyeZ * H;
    float rowDist = abs(posZ / denom);
    rowDist = max(rowDist, minDist + 0.02);

    vec2 wp = ro + rd * rowDist;

    uint cell = 0u;
    ivec2 cp = ivec2(floor(wp));
    if (inBounds(cp))
        cell = cellAt(cp);
    uint tcell = cellType(cell);

    if (p > 0.0)
    {
        uint tile = atlasForFloorCell(cell);
        vec2 tuv = fract(wp);
        vec4 tex = sampleAtlas(tile, tuv);
        return vec4(tex.rgb, 1.0);
    }
    else
    {
        uint tile = atlasForCeilCell(cell);
        vec2 tuv = fract(wp);
        vec4 tex = sampleAtlas(tile, tuv);
        return vec4(tex.rgb, 1.0);
    }
}

// Find nearest sprite intersection (by depth) within (tMin, tMax), and compute its color.
// If the nearest sprite is fully transparent at this pixel, we return alpha=0 but still
// report hitDist so the caller can advance and look for the next thing.
struct SpriteHit
{
    bool hit;
    float dist;
    vec4 color;
};

SpriteHit findNearestSprite(vec2 ro, vec2 rd, float py, float pitch, float eyeZ, float tMin, float tMax, int spriteCount)
{
    SpriteHit sh;
    sh.hit = false;
    sh.dist = 1e30;
    sh.color = vec4(0.0);

    float H = pc.a.y;
    float centerY = (H * 0.5) + pitch;

    vec2 right = vec2(-rd.y, rd.x);

    for (int i = 0; i < spriteCount; ++i)
    {
        vec2 sp = sprBuf.sprites[i].posSize.xy;
        float z = sprBuf.sprites[i].posSize.z;
        float size = sprBuf.sprites[i].posSize.w;

        vec2 toSp = sp - ro;
        float t = dot(toSp, rd);
        if (t <= tMin || t >= tMax) continue;

        vec2 closest = ro + rd * t;
        vec2 delta = closest - sp;

        float halfW = 0.35 * size;
        float perp = dot(delta, right);
        float lateral = abs(perp);
        if (lateral > halfW) continue;

        float lineH = (H / max(t, 1e-4)) * size;
        float spStart = (-lineH * 0.5) + centerY - (z * lineH);
        float spEnd   = spStart + lineH;
        if (py < spStart || py > spEnd) continue;

        // Nearest sprite so far.
        if (t < sh.dist)
        {
            float u = 0.5 + 0.5 * (perp / max(halfW, 1e-6));
            float v = (py - spStart) / max(lineH, 1e-6);

            uint tile = sprBuf.sprites[i].meta.x;
            vec4 tex = sampleAtlas(tile, vec2(u, v));

            // Slight lighting to help the sprite sit in the world.
            tex.rgb *= 0.95;

            sh.hit = true;
            sh.dist = t;
            sh.color = tex;
        }
    }

    return sh;
}

void main()
{
    vec2 res = pc.a.xy;
    float w = res.x;
    float h = res.y;
    float time = pc.a.z;
    float overlayAlpha = clamp(pc.a.w, 0.0, 1.0);

    // Early out: if game alpha is zero, this layer should contribute nothing.
    if (overlayAlpha <= 0.0)
    {
        outColor = vec4(0.0);
        return;
    }

    // Pixel coordinates in the render target.
    vec2 frag = gl_FragCoord.xy;
    float px = frag.x;
    float py = frag.y;

    // Camera
    vec2 ro = pc.b.xy;
    float ang = pc.b.z;

    float eyeZ = clamp(pc.c.x, 0.05, 0.95);

    int spriteCount = int(pc.c.y + 0.5);
    spriteCount = clamp(spriteCount, 0, 256);

    int maxHits = int(pc.c.z + 0.5);
    maxHits = clamp(maxHits, 1, 16);

    // FOV (about 66 degrees like classic Wolf3D)
    float camX = (2.0 * (px / w) - 1.0);
    vec2 dir = vec2(cos(ang), sin(ang));
    vec2 plane = vec2(-dir.y, dir.x) * 0.66;
    vec2 rd = normalize(dir + plane * camX);

    // Pitch (pixels: positive looks down)
    float pitch = pc.b.w;

    // Background floor/ceiling (opaque by default)
    vec4 bg = shadeFloorOrCeil(ro, rd, py, pitch, eyeZ, 0.0);

    // Accumulate nearest-to-farthest, premultiplied.
    vec3 accum = vec3(0.0);
    float remain = 1.0;

    bool allowExit = false;
    bool exited = false;

    float tCur = 0.0;

    for (int hitN = 0; hitN < maxHits && remain > 0.003; ++hitN)
    {
        float tMin = tCur + 0.001;
        vec2 ro2 = ro + rd * tMin;

        Hit wh = traceRay(ro2, rd, allowExit);

        if (wh.exited)
        {
            exited = true;
            break;
        }

        // Absolute wall distance from original ro
        float tWall = tMin + wh.dist;

        // Find nearest sprite in front of this wall
        SpriteHit sh = findNearestSprite(ro, rd, py, pitch, eyeZ, tMin, tWall, spriteCount);

        if (sh.hit)
        {
            vec4 sc = sh.color;
            float a = clamp(sc.a, 0.0, 1.0);

            if (a > 0.001)
            {
                accum += sc.rgb * a * remain;
                remain *= (1.0 - a);
            }

            // Advance past the sprite depth (even if transparent texel, so we can see what's behind)
            tCur = sh.dist;
            continue;
        }

        // No sprite before this wall. Shade the wall.
        vec4 wc = shadeWallPixel(ro2, rd, py, pitch, eyeZ, wh);
        float aRaw = wc.a;

        // If the wall slice doesn't cover this pixel, nothing farther will either (classic projection).
        if (aRaw < 0.0)
            break;

        float a = clamp(aRaw, 0.0, 1.0);

        // Fully transparent texel (e.g., glass holes / door window): advance and keep tracing.
        if (a <= 0.001)
        {
            if (wh.type == TILE_GLASS)
                allowExit = true;
            tCur = tWall;
            continue;
        }

        // Only allow exit transparency if we have passed through a GLASS tile surface with alpha < 1.
        if (wh.type == TILE_GLASS && a < 0.999)
            allowExit = true;

        accum += wc.rgb * a * remain;
        remain *= (1.0 - a);

        tCur = tWall;
    }

    // If we exited through glass, the background is transparent (so layer 1 shows through).
    if (exited)
        bg = vec4(bg.rgb, 0.0);

    vec3 rgb = accum + bg.rgb * bg.a * remain;
    float outA = (1.0 - remain) + (bg.a * remain);

    // Apply user-controlled game layer alpha.
    outColor = vec4(rgb, outA) * vec4(1.0, 1.0, 1.0, overlayAlpha);

    // Tiny time-based shimmer on glass to keep it feeling alive.
    // (Only affects visible pixels, alpha unchanged.)
    float shimmer = 0.015 * sin(time * 2.1 + px * 0.03 + py * 0.05);
    outColor.rgb += shimmer * outColor.a;
}
